### ISSUE TITLE
TODOs for Query, a new class for bot interaction

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#104]
As discussed for #102, and directly with Alex [here](https://github.com/e-a-h/That-Sky-Bot/commit/85aba294264298ac097dd5a0187cb97e362b5522#commitcomment-37094200):

To make music-maker / bot interaction easier, it would be desirable to create a new class. The underlying reason is that a bot is conversational, i.e. it asks and answers questions in no definite order, while the music-maker script is a linear “old-fashioned” program with prompts (input() & print().

The code is being pushed in the dev branch.

TODOs:

- [x] finish QueryOpen
- [x] Think about how the asking locutor will “know” that it has been talked back
- [x] change the list of valid locutors from test strings to something else (objects? Class names?)
- [x] implement my secret hash-like feature and the corresponding functions in QueryMemory
- [x] try using the objects inside Communicator and bot to see how it works
- [x] add support for the Information class in `def store()` method of QueryMemory
- [x] add sorting by time stamp in QueryMemory
- [x] IMPORTANT: finish implementing the *prerequisites* property. In particular, for each Query check that the dependencies have been answered to. Currently the prerequisites is only used to make a topological sort.
- [x] let Tracey digest the code, test it with test_comm.py, give directions, make corrections, beautify it
- [x] enable the use of UIDs to define prerequisites (dependencies)? Problem: the UID is only created once the Query has been sent (or manually).

**Comment by jmmelko** [comment]
At this stage it is very important not to think in terms of python code, but in terms of real-life objects. For this reason, naming is very important.

For instance, if this new class is called Question, it should have several of these properties:

* a question is a request for information
* it has one or several formulations
* it has one or several possible answers
* it is repeated (or not) after a given time if no answer is given
* it is repeated (or not) if a blank answer is given
* for some questions there is a default answer (yes/no questions, and choice within a set, eg song key), for other not (open questions, such as “composer name”)
* a question has an “answered”/“not answered” status
* it is asked by a speaker
* it is asked to a responder/(listener)
* “answer” could be a property of question or a separate object
* the internal answer can be different from the answer you give out (for instance, the answer to ‘what is the song key?’ can be C, but you give the answer 'do' instead).
* finally, some questions may be inter-dependant. So, if a previous question has not been answered, the question may be asked differently, or not asked at all, or the answer can be different, or undetermined. (For instance, song key depends on song notation)
* etc

**Comment by jmmelko** [comment]
There is a subtlety here: for the moment questions are asked by the Music Cog to the player via the bot (« what is the title? » « What are the notes »?), but it’s not impossible that one day questions are asked the other way.
Even now, you could say that the bot asks Music Cog: « what is the first PNG output for this song? », or « what was the title already, because I forgot ».
Later, if the database of songs is implemented, clearly the player via the bot will ask things such as « what is the latest song uploaded to the database? » or « Give me the top ten downloaded songs ».  Clearly, these questions will be handled (answered) differently from other questions: I suppose they will be translated to an SQL query, or a method using several SQL queries. Nevertheless they could still use the Question class.

Failure to anticipate this may lead to hazardous results:
https://youtu.be/0D7hFHfLEyk

**Comment by jmmelko** [comment]
I have created a new class called Answer.
For the moment, I have assumed that the bot would create this object, passing the question as a reference during initialization. And then, after building the answer, it would transmit (append) Answer to Question, using a method of Question. Or something like that (Question.set_answer(Answer)).
The Answer variable would then live outside Question.
But there are other ways to do that.
For instance, the Answer object could be created by Question itself, inside a method (def set_answer .... self.answer = Answer()). Then the Answer would be a variable living inside Question. I think it is what was initially intended.

That’s a work in progress so feel free to change the code’s logic.

After that we need to implement the questions. I have listed them at the top of the question.py file.

At some point I had the idea of creating only 3 questions classes, one for each question type (Boolean, choice, open), and then passing the subject of the question as a parameter (“song-title”, “music-key”).

But I have carried on in creating a class for each subject: QuestionSongMetadata, QuestionSongKey, QuestionNotation...

I don’t know which is best.

Finally, we may have to distinguish between very open questions (eg free strings), and open questions with type/range limits (eg 12 < octave_shift < 12). This control is easier to implement with my second choice of creating a class for each subject.

**Comment by t1-tracey** [comment]
Thanks JMM, I will look over the changes (but won't be able to work properly on it again until next weekend)

I like the idea of `Question.set_answer(Answer)`

> At some point I had the idea of creating only 3 questions classes, one for each question type (Boolean, choice, open), and then passing the subject of the question as a parameter (“song-title”, “music-key”).
>
> But I have carried on in creating a class for each subject: QuestionSongMetadata, QuestionSongKey, QuestionNotation...
>
> I don’t know which is best.

oh I was thinking 3 question classes for the question types. And then QuestionSongMetadata, QuestionSongNotation etc.inherit from those. (SongKey and SongNotation are choice questions)

(I'm not sure whether to make them classes or instances, was trying to read here: https://stackoverflow.com/questions/394770/override-a-method-at-instance-level there is a selected solution but an answer below it with many more votes)

btw for the options part of build_question, this was intended for QuestionType.Choice, so I have removed this code from QuestionText:

```
        if self.get_choices() is not None:
            self.question += '\n'

        for i, choice in enumerate(self.get_choices()):
            self.question += str(i) + ') '
            self.question += choice + '\n'
```

And yeah about the range limit questions, I think another question type might be needed too

**Comment by t1-tracey** [comment]
oh wait, I forgot that I was also thinking about rather than Question and Answer classes: how about renaming Question to Query, and the answer is stored in Query.result ? 

This was because Question is also the name of a class in the Discord bot (await Question.ask), and because of what you said about Answer almost being not different to Question. sorry I should have brought it up earlier

**Comment by jmmelko** [comment]
Ok for making Question inherit from 3 major types.
Actually since I have created QuestionText I will have to use multiple inheritance (eg QuestionKey inherits from QuestionChoice and QuestionText), but that’s ok. we’ll see.

Ok for renaming question to query.

Then in this case I will also rename answer to result so as to have: Answer.get_result() instead of Answer.get_answer().
Or better, I will rename Answer to Reply.

Thinking about it, Question/Answer was alluding to a teacher asking something they already know to its pupil.

**Comment by jmmelko** [comment]
Btw it is not possible to import Answer from Question.py and Question from Answer.py.
Because when importing all the module is read and it creates a circular reference, resulting in an error.

I had this problem with NoteParser and English and I solved it by writing the import English sentence inside the function, and not at the top of the file.

It is generally agreed that if two modules are calling each other and are linked, they should be in the same file.

So I will put both in queries.py (I would have preferred dialog.py but dialogs with an s is already a Python package), and we’ll decide later if we want to split them again, and how.

**Comment by t1-tracey** [comment]
Oh I didn’t realise when I put them in separate files, please feel free to put them back in the same file^^

Sent from my iPad

**Comment by jmmelko** [comment]
Tracey,

Could you please tell me what kind of information would return get_information_before()?
With  an example if possible.

Thank you.

**Comment by t1-tracey** [comment]
oh yeah at the time I was thinking for this for example:

```
    def ask_song_headers(self, song_key):
        self.output('\nPlease fill song info or press ENTER to skip:')
        original_artists = self.ask('Original artist(s): ')
        transcript_writer = self.ask('Transcribed by: ')
        self.get_song().set_headers(original_artists, transcript_writer, song_key)
```

`'Please fill song info or press ENTER to skip'` is information before the actual question is asked.  I am not really sure how to structure things

**Comment by t1-tracey** [comment]
oh I am looking through `communication.py`, and Query and Reply make sense to me

**Comment by jmmelko** [comment]
“Answer” is a left over from the changes.
It is only query.result vs reply.result

**Comment by jmmelko** [comment]
> `'Please fill song info or press ENTER to skip'` is information before the actual question is asked. I am not really sure how to structure things

Ok this is foreword to the question. I’m not sure yet it is necessary, but we’ll keep them.
I suggest to rename them foreword and afterword (other possibilities include preface/postface, opening/closing, prologue/epilogue, introduction/conclusion, preamble/appendix).

**Comment by t1-tracey** [comment]
oh yeah I just read your terms, I prefer those a lot more :blush:

**Comment by t1-tracey** [comment]
Ok I think I have an idea of how to set up the questions now (make them instances of the different Query classes. note_shift will need a method to be overridden, perhaps, to make sure the answer is in range)

**Comment by jmmelko** [comment]
Yes, actually, there are two options from here:
* add optional arguments to the major Query classes to check the answer type
* create a new Query type for each  kind of information

For the first option te arguments could be something like:
* type (the expected class name, eg list, str, int, Image, file, to be checked with an isinstance(), or a custom-defined type in an enum, “string”, “file”, and then it’s up to us to write the correct checking procedure)
* range (eg 1-7 for numbers, a regular expression for characters)

I think we should use the enum to define the data type, not the query type, which is already defined by the class (so at the moment they are redundant).

**Comment by jmmelko** [comment]
Tracey,

I suppose that afterword is the text you want to write after the question? (So It will be blank most of the time.)

**Comment by t1-tracey** [comment]
Yeah I planned it for any text after the user has replied.

Sent from my iPad

**Comment by jmmelko** [comment]
I have made progress and introduced an exciting (and probably useless) feature called QueryMemory.

I still have to decide how reply and query will interact, I think Tracey has said that the reply object should be created inside Query.

I have to stop for now I’m going to the theater and I don’t want to be rude coding in the line :-))

**Comment by jmmelko** [comment]
I have made progress and introduced an exciting (and probably useless?) feature called QueryMemory.

I still have to decide how to handle replies exactly.

For the moment a Reply is created by the Query (as Tracey wishes).
But I have not implemented the equivalent of build() and send() yet.

We’ll also have to decide how each locutor will know that it has been spoken to.

**Comment by t1-tracey** [comment]
Ahh oof, I hope you enjoy the movie

**Comment by jmmelko** [comment]
For the moment a Reply is created by the Query (as Tracey wishes, I think), via the receive_reply method.

I agree that this nesting of objects can be confusing. We’ll see in time.

Not that ‘question‘ is the main text of the question, while query.result is the complete formatted question.
Likewise, answer is the short answer while reply.result it the complete formatted answer.
Query and Reply are objects and theses names should never be used for something else (and certainly not strings).

We’ll also have to decide how each locutor will know that it has been spoken to. Maybe the QueryMemory object can help in this respect?

TODOs:

- [ ] finish QueryOpen
- [ ] Think about how the asking locutor will “know” that it has been talked back
- [ ] change the list of valid locutors from test strings to something else (objects? Class names?)
- [ ] Use the depend_on property
- [ ] address TODOs left in the code as comments
- [ ] let Tracey digest the code, give directions, make corrections
- [ ] revise methods names to avoid confusion, if necessary (question, result, check\_something, is\_something, send, get_\something)
- [ ] truly using the objects inside responder and bot to see how it works

**Comment by jmmelko** [comment]
Regarding depends_on:

* it should be renamed requires, prerequisites, requisites, requirements, prerequirements, predecessors, or anything sounding more coercitive
* obviously only the asker or the sender can know which Queries are required first. The Query and Reply objects, in themselves, are shallow vessels that do not understand what they are carrying
* so either the asker builds all the Query objects at once, and pass some of them as parameters, and then comparisons are made with the Query objects themselves: if all([required in queries for required in requirements]), then OK
* or, much more tricky: the asker only passes some partial information about the prerequired queries, for instance a string such as “key”, and the Query (or the receiver) asks QueryMemory to find this string inside a previous Query, recalls the Query, checks it’s valid, and then says the requirement has been satisfied.

**Comment by t1-tracey** [comment]
yeah I think those names are suitable for it, more than depends_on ^^
wow I did a first run of `test_comm.py`, I'm so excited 😆 yep I definitely need time to process, but really looking forward to setting up our questions from the music sheet maker soon 😮

**Comment by jmmelko** [comment]
> yeah I think those names are suitable for it, more than depends_on ^^
> wow I did a first run of `test_comm.py`, I'm so excited 😆 yep I definitely need time to process, but really looking forward to setting up our questions from the music sheet maker soon 😮

Well maybe depends_in was not so bad after all.

Anyway, I think you can start to play with it.

I need some feedback to progress on depends_on and replies.
I have created a QueryMemory class, which is able to sort Queries. I think it would be useful if one day we want to address queries in a non-linear, asynchronous way.

**Comment by t1-tracey** [comment]
I much prefer working with the new Query classes 😍 I am experimenting with a prototype, but found there's still more work to be done before we can use the Query classes in the bot — 

1. I saw these, I think they are so suited for using in the Discord bot. I'm really happy, I just wanted to say thank you for the send/receive approach:
```
q_open.send()
q_open.receive('example answer')
```

2. I saw unique identifiers for the queries after I updated to latest dev, I think that'll really helpful (before that, I was wondering how to get a specific query from the brain/querymemory in order to let it receive a reply)

3. I noticed the term 'brain', I really like using the QueryMemory, but I was confused by the term 'brain', haha

I'll make two other TODO's

**Comment by t1-tracey** [comment]
About depends_on, I didn't really know how to address it actually — previously I was thinking the same, that basically the question order just has to be defined by us at the moment. And that maybe the query would do this as a basic check

```
for query in self.depends_on:
    check if query.is_answered == True

if not all true, raise Error
```

but I noticed the topological sort that you added now :+1: (still haven't looked through as deeply as I would normally like to).

about the two other issues, I think your TODO list can be kept here (and this issue will be focused for changes to the structure of Query and Reply and associated classes)

**Comment by jmmelko** [comment]
> I noticed the term 'brain', I really like using the QueryMemory, but I was confused by the term 'brain', haha

At first, I wanted to call the functions “remember”, “forget”, and then I switched to a more conventional vocabulary.

> topological sort

Yes, that’s just a snobbish term to call an algorithm that solves dependencies. Actually this is often used to install unix-like programs...
The one I used is called Kahn’s algorithm, and is a direct implementation of the pseudo-language algorithm found on the Wikipedia page:
https://en.m.wikipedia.org/wiki/Topological_sorting

Actually, if you pass the dependencies when you initialize the Query object, they will be almost sorted naturally, because you cannot pass an undefined variable. But if we add a dependency to an old object using a newly created object, things will get intertwined.

**Comment by t1-tracey** [comment]
Oh, I don’t think it’s snobbish - I understand the term topological sorting, with nodes and graphs ^^

**Comment by t1-tracey** [comment]
Would you be able to add support for the Information class in `QueryMemory.store()`? I can add it to the todo checklist above (might move it to the first post so the number appears in the issue)

**Comment by t1-tracey** [comment]
actually you don’t have to do it, i have just added it to the tasks. I am ok with doing the other issue btw

**Comment by jmmelko** [comment]
Wait wait wait: what is this new communication.Information class for?

Storing text?
Retrieving .yaml?

**Comment by t1-tracey** [comment]
Oh only so far for communicating:

• instructions from Parser to the bot/command line program 
• error ratio from Parser to the bot/command line program

**Comment by jmmelko** [comment]
> Oh only so far for communicating:
> 
> • instructions from Parser to the bot/command line program
> • error ratio from Parser to the bot/command line program
> 
> i was thinking it was just information rather than a Query, as one wasn’t requesting anything from another ... but tell me if you think an existing approach is better

I don’t know yet, I’ll see with an example.

If it’s communication *within* the Music Cog,  between internal classes, then probably using Query is not useful.
(Unless this internal communication becomes complex, especially if it becomes asynchronous with dependencies: in this case we’ll switch to Query).

Just a note about “error ratio”, and other pieces of information:
Currently it is a figure given to the player after the song is generated.
So, IMO, it is part of the answer to the question. In other words:
* Query from bot to cog: I want visual sheet for my song.
* Reply: OK, I am ready for you.
* Query from cog to bot: what are your notes?
* Reply: Ab, C#, D, F....
* Query from bot to cog: what is the visual sheet for the song I gave you?
* Reply: (PNG_images, Information)

where information is an object, a list, a tuple that contains, among other things, the error ratio.

Or, we can decide that Reply is only PNG_images. That is a Reply must be homogeneous.
In this case, the error ratio would be given as the Reply to the Query: what is the error ratio for the last song you gave me?

If it doesn’t suit the needs, then we’ll have to create a Reply_list object, which would be a list of different Replies objects.

It is important to realize that, in our communication protocol between the Cog and the Bot, we have *not* anticipated the case where one locutor (cog/bot) would talk to the other party without prior notice, or without being asked to first.

I agree that in everyday life, you can give information without asking a question. For example when you say hello to somebody, or when a policeman (or a street sign) blocks your car, or when the news are on the TV.
But even there you can see this as a Query/Reply exchange:
* “hello” is a Query that implicitly awaits a hello back
* “stop you car, sir”, is a Query that implicitly waits for you to stop your car, and/or nod to acknowledge the order
* “todays news are”, is a Reply to your Query “what’s on TV now?” after you push a button on your remote

**Comment by t1-tracey** [comment]
> It is important to realize that, in our communication protocol between the Cog and the Bot, we have not anticipated the case where one locutor (cog/bot) would talk to the other party without prior notice, or without being asked to first.

yeah I was thinking so too ^^ maybe a `send()` & `receive()` style protocol can help (e.g. 'I am ready to listen')

(btw I renamed it to music sheet maker rather than music cog - the music cog is inside the bot. The communication is between our music sheet maker program and the music cog)

the two cases so far, the music sheet maker needs to send the instructions to the player before starting a song:

```
===== VISUAL MUSIC SHEETS FOR SKY:CHILDREN OF THE LIGHT =====

Accepted music notes formats:

* Type on keyboard as you would in Sky:
   QWERT
   ASDFG
   ZXCVB

* Sky column/row notation:
   A1 A2 A3 A4 A5
   B1 B2 B3 B4 B5
   C1 C2 C3 C4 C5

* English (note name in C D E F G A B + alteration b/# + octave number, e.g. Cb4 D#4 E5 ...)

* Doremi (note name in do re mi fa sol la si/ti + alteration b/# + octave number, e.g. dob4 re#4 mi5 ...)

* Jianpu (note name in 1 2 3 4 5 6 7, followed by alteration b/# and several + or - for octave shift)

* Abbreviated English chord name (e.g. C, F, Dm, Bdim, A+, Csus2, Dsus4, C6, Cmaj7, Dm11)

Notes composing a chord must be glued together (e.g. A1B1C1).
Separate chords with " ".
Use "." for a silence (rest).
Use "-" to link notes within an icon, for triplets, quavers... (e.g. A1-B1-C1).
Add *2 after a chord to indicate repetition.
Sharps # and flats b (semitones) are supported for Western and Jianpu notations.
```

and the second case is:

```
Song successfully read with no errors!
```

```
Song successfully read with few errors!
```

```
**WARNING**: Your song contains many errors. Please check the following:
- All your notes are within octaves 4 and 6. If not, try again with an octave shift.
- Your song is free of typos. Please check this website for full instructions: https://sky.bloomexperiment.com/t/summary-of-input-modes/403
```

**Comment by jmmelko** [comment]
> yeah I was thinking so too ^^ hmm maybe a send() & receive() style protocol can help (e.g. before one sends information to the other, they ask 'are you ready to listen?' and wait for 'I am ready to listen' before sending)

Yes.
The only issue is that it starts to look like bot code. And we are not supposed to replace the bot, only to write a Cog. For instance I know that the “listen to” function already exists in the bot, along with triggers.
Nevertheless, maybe it will do good to adopt bot logic, though.

**Comment by jmmelko** [comment]
Task done.
#109 is its continuation.
