### ISSUE TITLE
Output is an HTML, not an image

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#11]
![untitled](https://user-images.githubusercontent.com/17069038/67997933-a230b980-fc56-11e9-9651-73a4cb50dd27.png)
my first output. Still some work to do with coordinates and CSS!

**Comment by jmmelko** [comment]
Making progress!

![Canon in C](https://user-images.githubusercontent.com/17069038/68062686-3a3caa80-fd0c-11e9-9687-aa5a498cb2b8.png)

**Comment by jmmelko** [comment]
Okay! First part almost done (converting to SVG).

I still have to handle long songs by splitting in several files. Because SVG are not scrollable, in contrast with HTML.

Next I will try conversion to bitmap using Pillow or ImageMagick.

Also, we have to decide what would be the default layout. Portrait or landscape?

![untitled](https://user-images.githubusercontent.com/17069038/68078045-30c84680-fdcf-11e9-8b01-5403e3a994a8.png)
![untitled2](https://user-images.githubusercontent.com/17069038/68078046-3160dd00-fdcf-11e9-98ac-21123f060370.png)

**Comment by t1-tracey** [comment]
This is really nice

**Comment by jmmelko** [comment]
Solved in beta.
(still need to be test thoroughfully, but it works).
