### ISSUE TITLE
Porting for online use

### ISSUE THREAD

**Issue by jdewfiez** [sky-music/sky-python-music-sheet-maker#117]
I'm currently trying to port this project for online use. (not Discord bot/version). Do I have enough permission to fork and rewrite some part of the project?
Thank you.

**Comment by jmmelko** [comment]
Hi,

I am currently writing a website using Django.

Give me a few days to solve bugs and then I can pass on the project to you if you like.

**Comment by jdewfiez** [comment]
Sure. I'll wait.

**Comment by jdewfiez** [comment]
By the way, before I create this "issue" I already made those following forks and projects:
Forked Repo: https://github.com/jdewfiez/sky-python-music-sheet-maker (5% rewrite for URL Parsing)
Website (with messy code): https://github.com/jdewfiez/skysheetmaker
What do you think?

**Comment by t1-tracey** [comment]
Wow this is cool
https://jdewfiez.github.io/skysheetmaker

Hm I get "Online maintenance" when I try to make a song, but I’m excited to see this.

> I'm currently trying to port this project for online use. (not Discord bot/version). Do I have enough permission to fork and rewrite some part of the project?

Yeah the choice is totally yours. The project is open source and under MIT license, it basically means you can modify it however you like. (The disclaimer just means that we are not liable for damage) 

Despite wanting to code/design, I’m basically around to answer questions these days

> I am currently writing a website using Django.
>
> Give me a few days to solve bugs and then I can pass on the project to you if you like.

I didn’t realise you were checking out Django, JMM. I think doing whatever you enjoy, and passing it onto someone else is great 👍

**Comment by jdewfiez** [comment]
> Wow this is cool
> 
> https://jdewfiez.github.io/skysheetmaker
> 
> 
> 
> Hm I get "Online maintenance" when I try to make a song, but I’m excited to see this.
> 
> 
> 
> > I'm currently trying to port this project for online use. (not Discord bot/version). Do I have enough permission to fork and rewrite some part of the project?
> 
> 
> 
> Yeah the choice is totally yours. The project is open source and under MIT license, it basically means you can modify it however you like. (The disclaimer just means that we are not liable for damage) 
> 
> 
> 
> Despite wanting to code/design, I’m basically around to answer questions these days
This is getting great, thank you!

**Comment by jdewfiez** [comment]
> Hm I get "Online maintenance" when I try to make a song, but I’m excited to see this.

The server side haven't being worked on yet. Til I finish the rewrite, it will merged into the web app!

_I literally spend 8 hours writing a tool for better workflow, haha._

**Comment by jmmelko** [comment]
That’s a great alternative.

I’ll be able to show you my own version very soon, I just have to tackle with one last bug.

JMM.

**Comment by jdewfiez** [comment]
Upon different mode, what should I expect about the program asking for input like this one?![image](https://user-images.githubusercontent.com/34794115/77926912-e4772900-72d0-11ea-948e-058ab07f74d4.jpeg)

**Comment by jdewfiez** [comment]
Can I may chat with one of you asking how the program takes input? Thanks in advance.

**Comment by jmmelko** [comment]
I don’t have much time for chatting at these hours, I am more available between GMT 8h30-11h30.

Inputs are taken as text or numbers:
* if the question is open-ended, then you must give some text, such as one or several musical notes, a name, etc
* if the question is to be answered within a set of choices, then you have to enter the number of the choice in the order they are displayed in the list (0, 1, 2....). I have not implemented the possibility to type the choice instead (“English notation”) because it would require the program to do smart guessing in case of typos (as Google does).

**Comment by jmmelko** [comment]
http://jmmelko.pythonanywhere.com/

**Comment by t1-tracey** [comment]
> Can I may chat with one of you asking how the program takes input? Thanks in advance.

@jdewfiez sure I’m ok with this, feel free to post on either the forum or Discord:

https://discord.gg/ec4P25f
https://sky.bloomexperiment.com/latest
https://sky.bloomexperiment.com/t/sky-python-music-sheet-maker/102/1
