### ISSUE TITLE
Transfer ownership of sky-music-website to Sky-Music

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#119]
Hello Tracey,

I am about to transfer ownership of the Django website to the Sky music organization.
To make this possible you must first delete the fork you've made (I have applied your changes, feel free to double-check), this is a GitHub requirement.

After that, I'd like to discuss the visibility / rights of this project. I am not too fond of having the code made public, in particular I have left sensitive information in some place... Also, this would make the website easily duplicable by people on any website, with the possibility to do fishing of user's personal data, etc...
In any case, I'd like forking to be impossible. So we should  ask @jdewfiez to delete his fork, please. This is not a matter of property but rather security.

Thank you.

**Comment by jdewfiez** [comment]
I will delete the fork, thanks for mentioning.

**Comment by jdewfiez** [comment]
Brw I have a little change in the code, should I make a pull request before deleting it?

**Comment by jmmelko** [comment]
> Btw I have a little change in the code, should I make a pull request before deleting it? (make directory in `wsgi.py` universal)

Yes actually I saw your change but did not understood it completely, I thought it was for your fork to work on your machine running a local server.
In the meantime I have added other paths so please take a look at the code and make a new pull request.

**Comment by t1-tracey** [comment]
Just to confirm, I’ve deleted my fork now^^ I have class so I’ll check back late

**Comment by jdewfiez** [comment]
I also deleted the fork too, I'll check on the base code sometime, I was busy recently so I think I have to focus on my main project.

**Comment by jmmelko** [comment]
Ok, I have done it.

Tracey, you might receive an email asking for  approval.

**Comment by jmmelko** [comment]
Unfortunately GitHub does not propose to make a repository private for an organization (unless you pay a monthly fee).

So we’ll have to do with a public website.
I have removed the secret key from the code. Actually this key in itself is not so secret: it’s just that the key which is in the online website must not be known from visitors, ie should be different from the one on GitHub.
