### ISSUE TITLE
Quaver notation is ambiguous

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#12]
It is not easy to guess in which order consecutive notes arranged in a single row (triplets, quavers...) must be played.

**Comment by jmmelko** [comment]
I will either of the following:
* change the colors to those of a gradient map (rainbow, temperature, etc)
* add a little arrow for notes arranged along a scale (G A B C D... or D C B A G...)
* add a number?
* split quavers in mini-chords images

**Comment by jmmelko** [comment]
is the new color scale ok?
![untitled1](https://user-images.githubusercontent.com/17069038/68804945-23c71500-0663-11ea-83b9-44249d71f378.png)

**Comment by t1-tracey** [comment]
Ahh it looks really good 🤩🤩🤩

I think it makes sense 👍 I can see which is ascending and descending

Sent from my iPad

On 14 Nov 2019, at 8:16 am, jmmelko <notifications@github.com> wrote:

﻿

is the new color scale ok?
[untitled1]<https://user-images.githubusercontent.com/17069038/68804945-23c71500-0663-11ea-83b9-44249d71f378.png>

**Comment by jmmelko** [comment]
phew! I have read that rainbow is not intuitive because yellow stands out, and the color order is not intuitive.
Viridis is supposed to be more intuitive. I have chosen yellow to be the first note because it stands out.
Other choice are possible, I have written scripts so that we don't have to manually generate all the files.
