### ISSUE TITLE
Prompts lack pedagogy

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#120]
Now that the sheet maker is online on a website, I realize that the questions lacks pedagogy and even in some cases the English is incorrect.

For instance: “do you want to shift by n octaves” ?

I will improve the stock_queries in communicator.py.

Maybe we will have to create a property such as “bullet tip” or “example”, that would be invisible to the command line, but could be used by website (and the bot) to give more hints to the player hints on how to type input. However, these hints would be invisible to the command line which is for developers and advanced users.
What do you think Tracey?

**Comment by t1-tracey** [comment]
Yeah I was thinking small text can help e.g.:

![Screenshot of Discourse login form](https://user-images.githubusercontent.com/22441348/78343499-a6d31280-75e6-11ea-8f7c-0600abc7b1eb.jpeg)

But I also want the program to be interactive, not sure how to facilitate that though. This was an early mock up I made before we developed the command line version into what it is today

![Brainstorming idea](https://sky.bloomexperiment.com/uploads/default/d3a134b4a94c48a83fb81fab512b2750962edd4d)

This mockup was one that I made after two other friends (AstroGerbil and GreyOldTwit) suggested on the discord server, that they wanted an online version (this matches the current fields available in the command line more)

![IMG_3530](https://user-images.githubusercontent.com/22441348/78343952-590ada00-75e7-11ea-83c0-2036eb83eaed.png)

**Comment by jmmelko** [comment]
Wow, this looks great.

Actually, the current version is nothing more than the command line versio with dynamically generated forms.
I am currently working on displaying several forms on the same page when they have no prerequisites.

Beyond that, if we want to do what you thought in the earliest days, we will have to create the forms on the website side, “hard” in the code.
This would still work with the current music maker. However, if we create a new question on the music maker side, we will have to create it in the website side. While currently there is no need for this.

Maybe later, my energy is not infinite.

**Comment by jmmelko** [comment]
I have created (not committed yet) a .help property that will be accessible by typing ‘?’ in the stdout and pressing a button on the website, and a tooltip that will be systematically shown in the stdout and displayed as a grey text on the website.

Please don’t alter too much the templates in the meantime to facilitate merging.
