### ISSUE TITLE
Onboarding users new to the syntax 

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#126]
We have some syntax that is unique and I think a wall of text might be intimidating

![Screenshot of DM with thatskymusic bot, with instructions for the music sheet maker](https://user-images.githubusercontent.com/22441348/79038047-a9062400-7c19-11ea-814e-cff4926edbc1.jpeg)

Currently, I’ve created these two guides:
https://sky.bloomexperiment.com/t/summary-of-valid-note-names/403
https://sky.bloomexperiment.com/t/sky-music-sheet-maker-syntax-reference/745

I wonder if an interactive tutorial could be made, to understand spacing notes, adding rests, adding comments etc.
This is an example of a tutorial for Markdown
https://commonmark.org/help/tutorial/

**Comment by jmmelko** [comment]
Yes, actually, what we (actually, *you*) could do right now is replace this wall of text by a shorter, more friendly, welcome message.
With a link to your tutorial.

This welcoming message would end by: “type ? for help after any question. Type ? right now for a list of supported note formats”.

Then, the detailed instructions can be put in the help_text category, which is displayed after typing ?.

**Comment by t1-tracey** [comment]
I can replace the text in the yaml file with a link (I'll copy out the French and Vietnamese translations)

**Comment by t1-tracey** [comment]
Hm I may need to complete tasks #75 and #99 for an interactive tutorial to work

**Comment by jmmelko** [comment]
Tracey, would it be wise to pull the code to beta before doing this?

**Comment by t1-tracey** [comment]
Yeah let’s pull to beta
