### ISSUE TITLE
Create Japanese do re mi 

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#128]
Create a new doremi parser with the Japanese katakana for Doremi

![image](https://user-images.githubusercontent.com/22441348/79058239-b15c6e80-7cae-11ea-807b-cec3c042251b.png)

https://twitter.com/verrat_m/status/1244451925749202945?s=20

**Comment by t1-tracey** [comment]
I can do this since I can read/write Katakana

**Comment by t1-tracey** [comment]
It worked!! (besides the issue of using spaces from the Japanese keyboard, which I opened another issue for)

**Comment by jmmelko** [comment]
It’s good to see you back in action.

Be aware that Easter’s holidays are quite short though ;-)

**Comment by jmmelko** [comment]
Btw Lang cannot open the Japanese file because of Unicode errors.
You have to specific the encoding when reading the file.
I have added an ‘ignore’ flag as week to prevent any error raising

**Comment by t1-tracey** [comment]
Ah thank you for specifying the encoding^^
And haha yeah I am so happy to be able to work on this again 😆 you’re right it’s too short...

**Comment by t1-tracey** [comment]
the task of creating the doremi_jp parser is done, we'll use new issues for any bugs (I'll continue on #133 )
