### ISSUE TITLE
Allow unicode sharps and flats as synonyms

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#129]
Possible approaches:

- add a method in `python/noteparsers/noteparser.py` to replace unicode sharps and flats with (# b)
- replace Unicode sharps and flats in the CHROMATIC SCALE DICT and regexes of each note parser (our sharps `#` and flats `b` are currently hard-coded in there...)

**Comment by jmmelko** [comment]
Tracey, why do you say that option 2 would be a lot of work?
we could use an 'or' statement inside the regex and use the Unicode directly inside it, provided we add an Unicode escape character before the regex:

    re.sub(ur'\u266|#')

of course we have to check that this escape does not prevent recognition of other characters.

**Comment by jmmelko** [comment]
Tracey,

I have added the two symbols in the regular expressions. This was simpler than using /uxxx codes. To be sure, I have forced Unicode encoding of the file as a comment header. This is Python 3 only.

Please tell me if it works (on an old song + a japanese song).

(Note that in the regex, you had written [b#] meaning that a note such as A#b4 would be recognized. In theory we should have written [b|#] to accept only one alteration. But I prefer the regex to be more tolerant.)
