### ISSUE TITLE
switch default icon_delimiter to \s rather than ' '

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#130]
`\s` should include other whitespaces

The default space in Japanese keyboard does not work with our current icon delimiter of space e..g

C D E F G A B

This:
ド　レ　ミ　ファ　ソ　ラ　シ

becomes this:

![image](https://user-images.githubusercontent.com/22441348/79059892-c3480c80-7cc2-11ea-9812-9c11c517b556.png)

expected result:

![image](https://user-images.githubusercontent.com/22441348/79059918-f8545f00-7cc2-11ea-960b-6fbfb082377f.png)

**Comment by jmmelko** [comment]
I agree and besides it will make bug no 6 of the website easier to solve.

**Comment by t1-tracey** [comment]
Hm I'm a bit stuck. when I try to replace the `' '` with `r'\s'` as a test, there is still an error with this line:

```
line = re.sub(re.escape(self.icon_delimiter) + '{2,' + str(max(2, len(line))) + '}', self.icon_delimiter,
                      line)  # removes surnumerous spaces
```

I'm wondering if we should just not have `icon_delimiter` as a parameter that the user can change, and make it `\s` by default throughout the program

**Comment by jmmelko** [comment]
You should not set icon_delimiter = r'\s', but '\s'

r is an escape code for regular expressions.

The character itself is '\s'

Just like '\n' is the new line character. We never used r'\n'

if you have re.espace(r'\s') then escaping is done twice, I don’t know how it works.

Hope it helps. Otherwise I will take a look

**Comment by t1-tracey** [comment]
Ah ok, yeah I set it to `'\s'` before I tried `r'\s'` and I also got an error on that line. I think I need help^^

**Comment by jmmelko** [comment]
The problem with regex is that you must use them completely, or none at all, or else you have escaping problems.

What I did is allowed ‘\s’ to be the only regex in delimiters

please check that a normal song is parsed correctly, and that a japanese one also.

After that, you can close I think.

**Comment by jmmelko** [comment]
This feature raised many bugs.
I think most of them are solved now.
