### ISSUE TITLE
Split SongParser into MeasureParser, InstrumentParser, etc

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#131]
The four would then be:

- SongParser
- MeasureParser
- IconParser / ChordParser / InstrumentParser
- Noteparser

The more modular it is, the easier it is for me to utilise specific parts in an interactive tutorial

Also I was trying to debug an issue that occurred after changing our icon_delimiter, and it was hard to look through the file (`songparser.py` is about 400 lines long)

***

I'll assign myself this, but probably I'll set it to be later down the line.

**Comment by jmmelko** [comment]
I can’t believe Song Parser is still 400 lines long even though I moved parsers into note parsers! 😭

**Comment by jmmelko** [comment]
See also #99

**Comment by jmmelko** [comment]
Do you know if we should create one file for each class (eg song_renderer.py: class SongRenderer) or if we can just put the object inside a file, with the first letter in  Uppercase as did Alex with Lang?
What are the recommendations?
I think the latter is more suited to what we want to do with the parsers, I think creating a class is a bit overkill. Unless we create a generic class parser and derive their classes from it, but is is really necessary?
