### ISSUE TITLE
japanese note parser incomplete

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#133]
Tracey,

I think you have forgotten to set the self.not_note_name_regex  inside doremi_jp

I think you have to put in it every allowed characters to describe a note, including sharps and flats (and negating the regex with ^).

**Comment by t1-tracey** [comment]
Yeah I was going to ask, what is the **not** _note_name regex for?

**Comment by jmmelko** [comment]
It is used in find_keys to eliminate everything that is not a note.
Then, the algorithm parsed each to detect if it belongs to the current investigates input_mode.
Maybe there is a another way, but I found it was easier to create this regex instead of combining  several logical statements.

**Comment by t1-tracey** [comment]
Ah ok I see about the use case (I just discovered about the use of the caret ^ in certain cases to mean 'not'. I only knew about it meaning 'start' and didn’t understand the regex. I understand now :D)

**Comment by t1-tracey** [comment]
Ok I filled in the not_regexes now, let me know if there are any issues
