### ISSUE TITLE
Anticipate people typing notes without spaces

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#137]
Add “don’t forget to use spaces” in stock_query/instructions_xxxxx

Another possibility is to detect if a user does not use spaces at all, something like:
    if num_spaces / len(notes):
    self.note_delimiter = ''

but it is not impossible that this would lead to errors in other cases...

**Comment by t1-tracey** [comment]
Oh it’s ok this is something I will cover in the song_tutorial

And I have included it in the reference either way:

 
![IMG_3564](https://user-images.githubusercontent.com/22441348/79166364-53ec2d00-7e28-11ea-85ea-8066a325e23c.jpeg)

I think it would clash with the chord syntax, to allow people typing notes without spaces. so I hesitate about allowing it.
