### ISSUE TITLE
Convert current resource accesses to use importlib

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#141]
As suggested by Jirassok, maybe the icones (images in elements) should be retrieved from a call to a resources class, instead of having:
`self.A_circle_png = os.path.normpath(os.path.join(self.directory_elements, 'A-circle.png'))`

for instance:
resources.py
base_dir = .....
`class elements`
     my_dir = path.join(base_dir, ....)
     A_circle = path.join(my_dir, (A_circle.png')

Of course, the paths would still be stored inside Notes

**Comment by t1-tracey** [comment]
Oh they suggested this:

```
from importlib import resources
import io
from PIL import Image

Image.open(io.BytesIO(resources.read_binary(
    'skymusic.resources.elements', 'A-circle.png'))
```

to avoid hard coded paths:

> The other issue is that the project's resource files (and output directory) are all accessed using hard-coded paths relative to project or source code. This makes it harder to include the resources in the package with setuptools, and it makes it harder to run the program from another directory.

**Comment by t1-tracey** [comment]
I’ll just link the issue here for reference 
https://github.com/jirassimok/sky-python-music-sheet-maker/issues/1

**Comment by t1-tracey** [comment]
The resources is a folder rather than a class, I think... and it is already made now, following this:

```
/
├── .gitignore
│   ⋮
├── setup.py
└── src/
    └── skymusic/
        ├── __init__.py
        │   ⋮
        ├── instruments.py
        └── resources/
            ├── __init__.py
            ├── css/
            │   ├── __init__.py
            │   ├── main.css
            │   └── warning.css
            └── elements/
                ├── __init__.py
                ├── A-circle.png
                │   ⋮
                └── unhighlighted-chord.svg
```
> With this, structure, you can access resources using importlib.resources.

**Comment by jmmelko** [comment]
Ok great, it was just a reminder.

**Comment by t1-tracey** [comment]
I think I won’t get to do more work on this for a while, having a group project for school too. (Easter break will be over for me)

**Comment by jmmelko** [comment]
Done.
Note that the importlib_resources module required for Python <3.8 requires the dist-info folders, in addition to the normal folders.
These folders are normally installed by pip, but not by pip under Stash for Pythonista.
