### ISSUE TITLE
I don’t think I'll work on the bot as the main program

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#142]
Looking back on the original idea I had for this project, https://blog.cactusicelight.com/sky-transcriber-spec/ I’m a bit bothered by a few things right now:

1. I initially suggested going in portrait mode for the pngs, like traditional pages of stave sheet music. The current landscape png only shows 4 lines per page (I don’t know how to edit the size yet). This means people have to flick pages more, and we also hit the Discord limit of 10 images per message a lot sooner.

![IMG_3569](https://user-images.githubusercontent.com/22441348/79422964-24dce380-8001-11ea-8c80-0a283f0cf8e2.png)

2. I think it’s unlikely that the people I intended to get use from this, will get use from a Discord bot. 

a) I have some Sky friends who don't play songs from any kind of traditional musical notation, and they don’t find the ABC1-5 notation helpful. This is why I originally had the Sky keyboard in my mockup, to input songs. The QWERT was intended as a test, to simulate this — not for text to be the primary form of input.

![mockup](https://blog.cactusicelight.com/content/images/size/w2000/2019/08/38AF24C1-669C-4E69-B5C4-3FFEDACF748A-1.jpg)

b) At the time when I was playing over the course of 2018, most people shared songs either by video, or teaching each other in game — by playing one line at a time and letting the other person follow. Even learning from video, people are often learning bit by bit — pausing, rewinding, practising parts over and over again. It’s unlikely that they’ll get that repetition from static sheet music without a keyboard to practice on. 

(This repetition for muscle memory tends to be kind of more important to learn a song on Sky, because it’s unlikely that someone has played an instrument with `3*5` buttons on a screen before)

3. With the songs being put on the Discord channel as PNGs, I think it will be difficult for most people to be able to look them while playing Sky. (Asking users to get another screen, or to print out the sheet music can be a lot of friction.) 

this is why I wanted the Sky keyboard on screen with the music sheet too.

If a player plays on iPad/tablet, at least they have the multitasking bar. In this case, our website only fits two columns of notes.

![IMG_3579](https://user-images.githubusercontent.com/22441348/79422745-c44da680-8000-11ea-8aa1-6a0746fd9062.jpeg)

Aside that, there’s probably a limit to how many columns can fit, before it becomes unreadable.

But a decent number of Sky players are on iPhone/phone, where there is no access to the multitasking bar.

As I was watching my friend Fiqo test the bot, I have to admit, I didn’t feel like he would get a lot of use out of it, without a lot of friction. He plays on iPhone for one thing.

**Comment by t1-tracey** [comment]
Let’s go back to "why make visual music sheets at all"

You may argue that the ABC1-5 or Western notation would fit in that multitasking bar. And I don’t have any problem with it or with people using it. It’s just that I wanted to make something else that worked for me, and for a number of my friends who also don’t find it helpful.

The issue I have with it, is that I don’t have associations with it as I do with traditional music sheet:

• I get little information at a glance, about which notes are aligned with each other. You might say that you can tell that A5 B5 are next to each other, due to the shared 5. But also B1 B4 share the same letter, and they are not next to each other. 

My brain cannot act quick enough to distinguish between shared numbers means next to each other, but not shared letters. (It’s helpful for seeing if they’re in the same row. But notes being in the same column tends to be more defining, for me to remember key parts of a song)

• I also cannot see patterns at a glance, from text notations. E.g. the text `A1 A3 A5`, `A1 A4 B1`, `A3 A5 B3` doesn't have a lot of evocability about these patterns:

![IMG_3580](https://user-images.githubusercontent.com/22441348/79425140-94080700-8004-11ea-96f9-e004cf5e1861.png)

• B3 B4 B5 C1 C2 does not give me strong visual indicator that the notes are going up (the 3 4 5 1 2)

**Comment by t1-tracey** [comment]
(I'm planning to send this to alexdolly too) Sorry this might have felt like being attacked...
I actually really appreciate the work that we've done so far

The closest experiences that I have to what I wanted the program to feel like from the spec, were these:

https://www.youtube.com/watch?v=AXC76X482lg
https://vimeo.com/358248560

What I want to say is, I decided that I will not spend time focusing on the music cog. I don’t mind if other people want to do it because it’s something that they enjoy. 

But it’s just personal for me that I want to spend my time only on what’s necessary, and I think people will not get the value out of the Discord bot, that I intend for them to. 

There is still value in cleaning up the parsers and renderers, and cleaning up how we import elements, (because those parts can be reused) so if I do continue to work on the program, I would still like to work on that.

Beyond that, yeah the spec I had is also beyond my abilities. I may start exploring web development then, I enjoyed looking at Ember JS as a framework when I was first messing about with ideas for this program. Or I may take a bit of a break for a bit. 

I do really value all the time I’ve spent working on this and collaborating with JMM, I feel like I’ve learnt and grown a lot.

**Comment by jmmelko** [comment]
As far as I am concerned, the music cog is finished.
It’s now up to Alex to put it in production.

**Comment by t1-tracey** [comment]
Yeah reflecting on it, the text input might be a more straightforward in terms of technical difficulty, than a what-you-see-is-what-you-get editor (same for Markdown vs a WSYIWYG editor for word processing)

I’m glad you’ve found the work helpful, in printing out sheets. Personally I use our music sheets as a fast way of playing songs, most of the time without having to memorise them too. 

There are a few other UX issues that I’m concerned with. One was:

- colour-coding quavers is an issue for people who experience colour blindness. My teacher is blue-purple colourblind, and another person in my class is red-green colourblind. I was reflecting on this when I brought up that I’d been working on this project. 

Yellow and green would be hard to tell apart for example, and more so that the colours used for the quavers are on a gradient and are pretty similar to each other,

> As far as I am concerned, the music cog is finished.
It’s now up to Alex to put it in production.
>
> I think it is time to finish cleaning the project directory and stop working on it. I can help for this last effort if you tell me what to do.

I appreciate the offer to fix up anything before you finish up. 

The changes I want are pretty major though (converting resource access and restructuring the project), so it’s ok if you don’t want to work on those now though.

About the project regardless, code often isn't a once-and-finished thing; it needs maintenance to ensure that it's fixed if something breaks 😅 it’s a bigger concern for the Music cog on thatskybot. Because if it breaks, and there’s no one to maintain it, it may as well just be removed. (The aim is to write as little code as possible, more code means more maintenance, making sure that it doesn’t break the rest of the program etc.) 

If we don’t want to maintain it in the long run, I think that we may as well not devote effort to putting it up (because for me personally, I’d rather focus my effort towards the spec I originally designed for, than maintaining the cog). And I would let alexdolly know. (Not sure if I mentioned yet, but I knew alexdolly, Sera, Nagati, Mirian way before this - they played since 2018 too. So it’s not too big of a deal)

I don’t mean to discount what you’ve done... it’s pretty awesome that you got it up. And that’s how I managed to test it with Fiqo and another friend. 
I just mean that if you stop here, I have no interest in maintaining it. And if it breaks, there might not be anyone to fix it...

***

Thanks for the change with adding Unicode sharps and flats.

I'm just going to keep myself open for anyone who’s more comfortable in Javascript, and might be interested in working on the project. There’s a bigger pool of Sky players, now that Android released. Yesterday I got a request from someone to upload songs onto the sky-music.github.io website, which was exciting

**Comment by jmmelko** [comment]
Ok maybe you’re right in the long run, but the result is that the music maker hasn’t been given any chance at all to run, besides on the command line.

What you propose is indeed reasonable, but not fun at all. For a child, it would be like building a complex Lego Model and not be allowed to play with it afterwards.

**Comment by t1-tracey** [comment]
I’m sorry, I can see you’re pretty upset. Maybe I’m wrong sorry... it probably isn't my decision as creator to decide what goes ahead. 

It’s my decision not to work on it sure, but it doesn’t mean other people can’t use the bot for what it is (and you’re right that people haven’t experienced it outside the command line before) Maybe they’ll find value that I don’t find in it
