### ISSUE TITLE
PNG rendering is a bit slow

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#15]

**Comment by jmmelko** [comment]
I think this is because each note is a new object which opens an image file when the render method is called. From note to note the same image is opened over and over again.
I could create an object which preloads all the image files into itself (and thus in memory), and retrieve properties of this object instead of image files.

**Comment by jmmelko** [comment]
I have found a way to be much faster by using non-transparent images (technically: PNGs without alpha channel).
So my question is: would it be acceptable if we decide that the background be always white?
It means that if we want to render chord images directly in a conversation in a Discord forum with a dark background, and not over a white paper sheet, the chord edges will look ugly because there will be white margins around.
We can still change the white to another color though, by creating new notes PNGs in the element folder.
Please advise.

**Comment by t1-tracey** [comment]
I think it would be okay if the background is always white :+1: 
I'm not sure what you mean by how it will look in discord hmm. do you think you can show me a song render using non-transparent PNG elements?

**Comment by jmmelko** [comment]
Yes, so, currently, in the master:
* The harp interior is always white, but it lies on a transparent background
* The font color is black, but can be changed
* The PNG background (paper sheet) is white, but can be changed
* All PNGs have a transparent background, so any change in  the PNG background, or even a change of the harp interior will be handled smoothly, I think

and in the beta:
* The harp interior is still white, but lies on a white background
* The font color can be changed to white to adapt on a dark background (but this has to be changed manually in the Instrument class)
* All PNGs have a white solid background, so if we change the PNG background color to the one in Discord, this gives:

![untitled](https://user-images.githubusercontent.com/17069038/68923559-de980580-077e-11ea-8c10-b9159b5ad992.png)

This can be "fixed" by changing the PNG background color to the one of the Discord forum.

However, if Discord decides to change its background color, we will have to make a change also.

**Comment by t1-tracey** [comment]
ohhh I see now~ I think I am fine with the whole global background colour being white, and the elements having the white background (non-transparent PNG). 

I like the idea of the music sheets being distinc images generated by the program, which you can also share outside discord

we won't have to worry about discord changing background colour either (and I also actually use light theme on discord)

**Comment by jmmelko** [comment]
I had a revelation: instead of generating un highlighted notes one by one, we should start from an empty chord image with all notes unhighlighted, and only paste highlighted notes.
This should save a whole lot of time.

**Comment by jmmelko** [comment]
Ok, png rendering now takes 0.9 sec for a 100-note-long song.
I think it has become reasonable so I close the issue.

Please test the beta just in case I missed to upload some changed files in github.

**Comment by t1-tracey** [comment]
Wow nice, I will test it when I have some time
