### ISSUE TITLE
Writing extended documentation on input notations

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#16]
I will write some documentation in the Wiki part of this repo https://www.divio.com/blog/documentation/

(still a work in progress)

![image](https://user-images.githubusercontent.com/22441348/68823274-66323580-06e7-11ea-857c-6ec61de57f6a.png)

**Comment by t1-tracey** [comment]
I'm ok with doing this one, just finding it difficult to code right now, I am sorry :(

**Comment by jmmelko** [comment]
When it comes to code, I prefer a bad document rather than no documentation at all.
Also, the doc will be useless if the program is integrated into the bot.
So don’t put it too hard on yourself :-)

JMM.

**Comment by t1-tracey** [comment]
hehe, I was planning to document it for when people will use the bot 😃 (not sure where the documentation will be put, just wanted to write it first) thx, I will take it easy

**Comment by t1-tracey** [comment]
Ok documentation will be put here: https://sky.bloomexperiment.com/c/music-sheet-maker/msm-documentation?kb=active
