### ISSUE TITLE
Parse HTML file back

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#173]
Several players would like to use visual sheets and feed them into sky studio.

What could be done:

1/ hide the notes in text format inside the HTML, so that they can be retrieved and parsed again

2/ write a script to retrieve notes from an HTML visual sheet

**Comment by t1-tracey** [comment]
I’ve heard that parsing HTML is unpleasant (option 2)

I had this request too

I think an alternative is to store the songs as JSON, and then the HTML is rendered from the JSON, and Sky Studio format is rendered from the JSON too
(The chord_skygrid is like JSON)

Or the other option that currently exists, is for players to keep the TXT

(These all not really ideal but they are options)

**Comment by jmmelko** [comment]
In the meantime I have hidden the ascii format inside the html. As a quick solution.
Doing everything form JSON would probably be better though.

**Comment by Specy-wot** [comment]
Aight I'll work on it now and see what I can do.

**Comment by Specy-wot** [comment]
Alright, I've made a pull request , this needs some testing tho since it affects all sheets

**Comment by jmmelko** [comment]
Done.
Thanks to Specy.
(Don’t forget to split the javascripts into 2 files)
closing
