### ISSUE TITLE
chord with lowercase letters produces error

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#19]
chords with lowercase letters seem not to be recognised currently (sky notation song transcribed by bait)

```
#dry hands d major
a2a5b2 b3 
a1a5 b1
a5b4 b3 b2 a1a3a5
a3 a5 b4 b3 b2 a2b1 a1 a2a5b2 a2b1
a3 a5 b1 a5 a2 a3 a2 a3 
b4 b3 b2 b1 a5 b2 
a2 a3 b2 a3 b4
a2a5b2 b3 a1a5 a3 b4
b1 b5 c2 a3 b2 b5
```

![Dry Hands by bait](https://user-images.githubusercontent.com/22441348/68908829-912c9000-07a0-11ea-9037-bf96f507cf59.png)

![Dry Hands by bait1](https://user-images.githubusercontent.com/22441348/68908830-912c9000-07a0-11ea-980c-951d67b10d1b.png)

in capital letters, this does work though :+1:

```
#dry hands d major
A2A5B2 B3
A1A5 B1
A5B4 B3 B2 A1A3A5
A3 A5 B4 B3 B2 A2B1 A1 A2A5B2 A2B1
A3 A5 B1 A5 A2 A3 A2 A3
B4 B3 B2 B1 A5 B2
A2 A3 B2 A3 B4
A2A5B2 B3 A1A5 A3 B4
B1 B5 C2 A3 B2 B5
```

![Dry Hands](https://user-images.githubusercontent.com/22441348/68908935-db157600-07a0-11ea-846c-722b36177112.png)

![Dry Hands1](https://user-images.githubusercontent.com/22441348/68908936-db157600-07a0-11ea-9868-9cd4fecfafc5.png)

**Comment by jmmelko** [comment]
Oops... probably a .upper() missing somewhere.
I’ll take a look.

**Comment by jmmelko** [comment]
Ok, you have to add:

chord = chord.upper()

in Parser.split_chord

just before the if conditions.

I fixed it in beta. I will add it in master.

**Comment by jmmelko** [comment]
I have fixed it but directly in GitHub, and I had to add spaces to indent, and not tabs, and since Python is very sensitive to indenting, I may have broken the master without realizing.

**Comment by t1-tracey** [comment]
oh I just tested master now, it worked fine!
