### ISSUE TITLE
Great but does not work with song_input_mode = 2 (fix proposed)

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#2]
Hi,

your script is great but returns an error with song_input_mode = 2 (ALPHANUMERIC).

Here are a few corrections to make:

* in the  parse_icon function you have to put the 'return tokens' instruction outside the if statement
* in the parse_chords function, for the case input_mode == InputMode.ALPHANUMERIC, you have to put the same lines as for the otehr case, that is :
                    is_empty = False
                    chord_image[highlighted_note_position] = {}
                    chord_image[highlighted_note_position][chord_idx] = True

I am currently writing an addition to import the codes from a text file.

**Comment by t1-tracey** [comment]
Oh that’s right, I hadn’t added support for the alphanumeric input node yet^^ thank you for letting me know about. Sorry I missed this message, set repository for watching now.

**Comment by jmmelko** [comment]
Actually my other alias is mimizan, so as you know from another forum I have solved the problem in my modified version.
When you have time, you are free to either import all of my changes or just the fix for the alphanumeric part. Sorry for not using the branches system of github properly.

**Comment by t1-tracey** [comment]
No worries, ok thanks so much. I like all your changes and I am going to merge them!
