### ISSUE TITLE
Website Error 

### ISSUE THREAD

**Issue by kleefu** [sky-music/sky-python-music-sheet-maker#217]
When clicking thenin site link to view visual sheet maker a system error text is shown instead with no work around. This prevents access to saved files and public songs please fix this soon! The error number is (500)

**Comment by jmmelko** [comment]
Ok, I’ll take a look to see if I can reproduce the bug at home

**Comment by jmmelko** [comment]
Problem fixed.
It was because of a font file not fully uploaded on the server (thank you iCloud).

**Comment by kleefu** [comment]
> Problem fixed.
> It was because of a font file not fully uploaded on the server (thank you iCloud).

Thank you so much! Darn icloud 😂
