### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by kleefu** [sky-music/sky-python-music-sheet-maker#221]
The website is inaccessible as of right now, showing the phrase “ coming soon This is going to be another great website hosted by PythonAnywhere.“ i am not sure if this is because the domian is no longer accessible or some maintenance is taking place but it seemed off and i figured here would be the place to seek answers.

**Comment by jmmelko** [comment]
The website has been relocated to eu.pythonanywhere.com

Was the link in your bookmarks or browser history?

or did you find an outdated link?

**Comment by kleefu** [comment]
Mkay no worries thank you!
