### ISSUE TITLE
Use '*' to denote repeat, rather than 'x'

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#26]
x may clash with the x in the QWERT ASDFG ZXCVB notation, I will need to check.

**Comment by t1-tracey** [comment]
ok I have been able to change the icon to be '*' when typing in a song, no more clashing with QWERT ASDFG ZXCVB

the images will still render 'X2' etc next to the note, as I feel this is readable still.

**Comment by t1-tracey** [comment]
oh it looks like the instructions at the start will print `\*`, not sure how to omit the backslash?

**Comment by t1-tracey** [comment]
ok managed to fix this, thanks to JMM's other example

**Comment by jmmelko** [comment]
Thank you for that. Since I added this feature 'shadowly', it was not properly implemented yet.
