### ISSUE TITLE
Fallen Down by Toby Fox

### ISSUE THREAD

**Issue by ponca3** [sky-music/sky-python-music-sheet-maker#273]
The print preview loads, but none of the "notes" are visible.  Please help!

![Screenshot (314)](https://user-images.githubusercontent.com/117777183/200673242-cb38774d-cf51-4090-9ce7-d5b7362069c5.png)

**Comment by jmmelko** [comment]
You have to check “print background” in the print settings.
Most likely this is hidden in the “more settings” panel
