### ISSUE TITLE
Transposition in the chromatic scale

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#32]
I think we are just a little tiny step behind being able to do transposition in the chromatic scale. Especially using the new functions developed by Tracey in the Western branch.

Here is the code to do it:

dodeca_sharps = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'] 
dodeca_flats = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B'] 

if note_shift != 0:
            (note_name, octave_number) = parse_western_note(note)
            if note_name != None:
               if note_name in dodeca_sharps:
                  idx = dodeca_sharps.index(note_name)
                  idx_shift = (idx + note_shift) % n
                  note_name = dodeca_sharps[idx_shift]
                  octave_number += math.floor((idx + note_shift)/n)
               elif note_name in dodeca_flats:
                  idx = dodeca_flats.index(note_name)
                  idx_shift = (idx + note_shift) % n
                  note_name = dodeca_flats[idx_shift]
                  octave_number += math.floor((idx + note_shift)/n)
               else:
                  print('This note has an error:'+note)
                  idx_shift = idx
               #build note string again
               note = note_name + str(octave_number)

***
todo's:

- [x] Decide whether the note_shift function is still useful

**Comment by t1-tracey** [comment]
about note_shift, I still actively need it — 

when transcribing a new song from my head that I know on piano, I usually use the octave numbers 1 & 2 for convenience. then I use note_shift to shift it up to octave 4

**Comment by jmmelko** [comment]
Ok, I’m just wondering whether an everyday player would understand what that means.
Shift is my own term for "transposition in Sky’s 7-notes scale".
Maybe should we improve the printed text in main.py, but I don’t have a clue how, yet.

**Comment by t1-tracey** [comment]
oh I do use note_shift on threshold, I have to use +21

I am ok with having this separate transposition file for transposition within the chromatic scale like you mentioned in the other issue

**Comment by jmmelko** [comment]
This is done in the dev branch:
* I have written a cleaner version of transposition.py that relies on main.py and parsers.py
* note_shift has been kept but shown to the user as an octave_shift (note_shift can secretely be done by entering a non-integer octave_shift, eg 1/7)

I am closing the issue as transposition.py works (at least for English notation and possibly doremi, I think it doesn not work for Jianpu but do we really care?), and we don't want to implement full transposition in the main script, we have other issues to tackle with, the bot is drawing near....
