### ISSUE TITLE
Bug in Western-Chord branch

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#33]
A return has been forgotten in method parse_western_note of WesternParser class:

if self.is_valid_western_note_name(western_note) == True:
                # Player has given note name without specifying an octave
                note_name = western_note
                octave_number = self.get_default_starting_octave()

**Comment by t1-tracey** [comment]
Oops thanks for picking that up, I’ll fix that hehe

Sent from my iPad

On 27 Nov 2019, at 8:43 am, jmmelko <notifications@github.com> wrote:

﻿

A return has been forgotten in method parse_western_note of WesternParser class:

if self.is_valid_western_note_name(western_note) == True:
# Player has given note name without specifying an octave
note_name = western_note
octave_number = self.get_default_starting_octave()

**Comment by t1-tracey** [comment]
oh looks like I do have it in the most recent version?

**Comment by t1-tracey** [comment]
you fixed it, ah I missed the commit T_T

**Comment by jmmelko** [comment]
Sorry about that.
I raised the issue not to forget, and then fixed it accidentally by a copy-paste, then went to sleep, and then realized that you would be confused, but then I was too sleepy to get out from bed 😴

JMM.

**Comment by t1-tracey** [comment]
Don’t worry hehe

Sleep is important ^^

Sent from my iPad

On 27 Nov 2019, at 5:22 pm, jmmelko <notifications@github.com> wrote:

﻿Sorry about that.
I raised the issue not to forget, and then fixed it accidentally by a copy-paste, then went to sleep, and then realized that you would be confused, but then I was too sleepy to get out from bed 😴

JMM.
