### ISSUE TITLE
Octave number doesn’t match scientific pitch notation (western-scales branch)

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#39]
Currently, when I set my song key to E major, C#2 is higher than E2 in the program.

This is because C#2 is regarded as 25₇, and E2 is regarded as 20₇ right now. In scientific pitch notation, C#2 is like (21)₁₂ and E2 is (24)₁₂.

The idea of C#2 being in the same scale as E2 was easier for me, since I already knew that i will play in E major. But there will be errors if a user is inputting a song in chromatic and expecting the program to decide on a key for them. So I will need to decide how to handle this later.

**Comment by t1-tracey** [comment]
Never mind I realised how to handle this now XD it’s fast, so I will patch it.

**Comment by jmmelko** [comment]
I don’t understand how this happens:

* your scale begins at 0 with C
* so E2 and C#2 should be correctly parsed as (E,2) and (C#,2)
* and then the chromatic equivalents: 4 and 1
* and then the intervals: 0 and -3

mmmhhh... Are you sure about this line:

if interval_in_semitones < 0:
            # Circular shift the interval back to a positive number
            interval_in_semitones += self.get_western_chromatic_scale_count()

Should you note update the octave number?

In my ugly transposition method I have something like this:
octave_number += math.floor((idx + note_shift)/12)

>

**Comment by t1-tracey** [comment]
yeah I just realised too, was just about to add octave_number -= 1 XD
