### ISSUE TITLE
Use brackets to denote chords

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#40]
Longer term, I think I would like to use square/round brackets for chords. E.g.

```
# first part
[ F# A C#2 F#2 ] G# [ F# A C#2 ] E2-F#2-G#2
[ E G# B E2 A2 ] B [ F# A C#2 ] G#
[ F# B D#2 F#2 B2 ] A [E G# B] C#3 E G#2
[E A C#2 G#2] [E A C#2 A2]
# second part
[ F# A C#2 F#2 ] F#-G# [ F# A C#2 ] E2-[G# F#2]-G#2
[E B F#2 A2] [E2 B2] [E A C#2 D#3]
[F# B D#2 F#2] E3 E3 [ G# C#2 E2 G#2 D#3 ] [G#2 C#3]
A2 B2
A2-G#2 A-G#2 G#2 B2-A2 A2-G#2
```

Initially the notes were glued together because I was typing with the keyboard QWERT ASDFG ZXCVB, and that was easiest. With single letters, it was ok to read, but the glued version of this song is difficult T_T

**Comment by jmmelko** [comment]
OK pour ascii rendering, but I’d like to keep this as optional for input.
Indeed, for songs In Sky notation, or for songs in western notation without sharps, the brackets result in a more complex song than without. Plus, there is a risk of forgetting a closing bracket. Several persons in the Discord forum agree, including Nagati.
We can create a note_in_chord_delimiter ='[' and choose to use it or not depending on the notation and/or the key and/or first try splitting with and then without.

>

**Comment by t1-tracey** [comment]
ah ok, yeah I'll guess I won't implement this yet then, depending on which is preferred

**Comment by t1-tracey** [comment]
I think the notation that Nagati was defending was `B123` for sky notation (the equivalent of `B1B2B3`)

I have seen some others use square brackets for chords, but we can come back to this if someone brings it up, it's not urgent right now

**Comment by t1-tracey** [comment]
(I have it at the back of my personal list if I want to revisit it https://sky.bloomexperiment.com/t/change-chord-notation-to-square-brackets/210/6 and I'll leave GitHub issues for the more current things we are working on)
