### ISSUE TITLE
TODOs for the WesternNoteParser parsers

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#44]
- [x] Test the WesternNoteParser — address any errors, make sure it works with some test songs, make sure the other notations (Jianpu, Sky etc.) are still working

- [x] Create test songs for all input modes

- [x] Test ascii output (and sky-western conversion)

- [x] Replace `find_key` with the new `find_western_key`.

- [x] In main.py, for finding keys, maybe could we implement allowing the user to choose from the top 3 possible keys if there is no perfect match? (Like with the modes)

- [x] Test what happens when several modes are detected

- [x] Remove (or comment) Jianpu2Western functions

- [x] Avoid using the old position_maps

- [x] rewrite detect_input_type

- [x] cleanup is welcome if you find anything
- [x] check that the coordinate of the western note is in the range of the Sky piano (0,0) to (2,4) before returning it, otherwise raise an error, so that a broken harp will be produced

- [x] Specifically test input_mode and music recognition

- [x] specifically test with dirty input (typos, missing octaves)

As for Jianpu and do re mi, I wasn't sure if they needed this NoteParser. But I just realised that maybe it could help to generate the coordinates rather than the long dictionaries currently used. I haven’t thought through this yet though.

- [x] finish implementation of Jianpu parsing
- [x] specifically test Jianpu and doremi parsing
- [x] check if the old trick to set pauses (breaks) to the (-1,-1) position is still used and/or that pauses are parsed correctly, including in find_keys and detect_input_type methods

- [x] before merging the western branch into the beta branch, archive the master in the stable

Any of these tasks are ok hehe

**Comment by jmmelko** [comment]
Yes, Jianpu and do re mi are different symbols for the same musical system. I mean, there is a 1-to-1 equivalence between them.
So they will rely on your Note Parser.

**Comment by jmmelko** [comment]
Wasn’ there a problem with ascii output also? (Apart from the use of the brackets due to the cluttering of sharps and notes)

JMM.

**Comment by t1-tracey** [comment]
Oh I realised what was wrong (ASCII output is working now). it was the bug where I had C#2 higher than E2 and the coordinates were out of range. thus the ASCII output was producing errors

Sent from my iPad

On 29 Nov 2019, at 10:16 pm, jmmelko <notifications@github.com> wrote:

﻿Wasn’ there a problem with ascii output also? (Apart from the use of the brackets due to the cluttering of sharps and notes)

JMM.

**Comment by t1-tracey** [comment]
oh never mind there is still a problem with ascii output T_T

ok the problem is, that the WesternNoteParser does not detect if the note's coordinate is out of range of the Sky keyboard, before returning it.

**Comment by t1-tracey** [comment]
I fixed the problem with notes that didn't have an octave number - they were producing the ascii errors because they were out of range. I added to the list at the top

**Comment by jmmelko** [comment]
Tracey,

I am currently rearraging the Parser class, so please don't do major changes wihout informing me first!
Don't worry, your NoteParser is OK. But to use it properly I have to redefine the way different objects and classes refere to each other.

**Comment by t1-tracey** [comment]
Oops I’m sorry about that, I’ll give a heads up next time.

And that sounds good!

Sent from my iPad

On 2 Dec 2019, at 12:26 am, jmmelko <notifications@github.com> wrote:

﻿

Tracey,

I am currently rearraging the Parser class, so please don't do major changes wihout informing me first!
Don't worry, your NoteParser is OK. But to use it properly I have to redefine the way different objects and classes refere to each other.

—

**Comment by jmmelko** [comment]
Ok I think everything is ok now.
I let Tracey make her own tests.

**Comment by jmmelko** [comment]
I have removed 1 to-do and created a specific issue for it #67

**Comment by t1-tracey** [comment]
I'll take a look at removing/commenting the Jianpu2Western functions now :D

**Comment by t1-tracey** [comment]
ok I've removed them for now rather than commenting, to keep `parsers.py` as lean as possible. but I have documented the legacy functions here:

https://sky.bloomexperiment.com/t/legacy-jianpu2western-functions/451

**Comment by t1-tracey** [comment]
since the last todo in this issue is deciding on note_shift, how about we move it to #32
