### ISSUE TITLE
Jianpu support in WesternNoteParser

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#51]
Tracey,

Your special note_parser for Jianpu works. But I still get errors with a Jianpu song, and I can’t trace them back. The error is not caught by your custom SyntaxError and KeyError exceptions.
Could you take a look? I’ll post my sample song in the branch.

Btw:

Is it necessary to search for note_base and note_alt separately? Couldn’t we use self.note_name_regex directly?
Besides, I think we should refer to regex as self properties and not use regex directly in the method.

I have changed

**Comment by t1-tracey** [comment]
Ah ok I’ll take a look at this~

Sent from my iPad
>

**Comment by t1-tracey** [comment]
I might not be able to handle it yet, but will take care of it once I’m back again

**Comment by jmmelko** [comment]
No problem. This is more a reminder than a real assignement.
We’re doing that for fun

**Comment by t1-tracey** [comment]
😄

**Comment by jmmelko** [comment]
Note 1+ is not in range of the two octaves of the Sky piano: (-5, 4)'
'Note 3+ is not in range of the two octaves of the Sky piano: (-4, 1)'
'Note 1+ is not in range of the two octaves of the Sky piano: (-5, 4)'
'Note 3+ is not in range of the two octaves of the Sky piano: (-4, 1)'
'Note 2+ is not in range of the two octaves of the Sky piano: (-4, 0)'

**Comment by jmmelko** [comment]
Fixed by adding self.get_default_starting_octave() to the octave
