### ISSUE TITLE
WesterParser bugs with octaves > 6 because of restrictive base 10 to 7 conversion

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#54]
trying to parse a note with an octave >6 results in an Error.

The reason for this is that, when the function convert_base_7_to_base_10 is called, the number written in base 7 is formed as follows:
str(octave_number) + str(major_scale_interval)

This is wrong if octave_number > 6, e.g. for 7 because '7' does not exist in base 7.
It should be '10'.

So... we should:

* write a convert_base_10_to_base_7 method
* convert the octave number (which is in base 10) to a str in base 7
* use this output string for the call of convert_base_7_to_base_10
* check that the latter functions can handle a base 7 number spanning two symbols (eg 10, 16)

NOTE 1: we don’t have to handle very large numbers. I think that 2 digits is enough (max number 66  in base 7)

NOTE 2: I advide against the easy solution of writting an exception such as "if octave > 6: raise error KeyError" because we should handle in octave first and then decide whether it is within the scale of the piano.)

**Comment by jmmelko** [comment]
Here is a crude method for n<14

    def convert_base_10_to_base_7(self, num):
    	
        numstr = ['0']*2
        numstr[-1] = str(num % self.get_base_of_western_major_scale())
        numstr[-2] = str(math.floor(num / self.get_base_of_western_major_scale()))
        return ''.join(numstr)

**Comment by jmmelko** [comment]
Ok I created a more generic function. I don’t know if it’s the fastest on earth, but that should do.
I leave the issue open for Tracey to take a look at it.

**Comment by t1-tracey** [comment]
oh I will take a look at this today, yep I remembered this issue occurring

**Comment by t1-tracey** [comment]
Ah I understand what you did, great work! I agree with the notes you mentioned, and how you approached converting the octave number into base 7 first.

**Comment by t1-tracey** [comment]
I think doing the generic function is good, you're right the crude method does only two digits, it was what I used in `convert_base_10_to_coordinate_of_another_base`. that can be changed later too, if needed.
