### ISSUE TITLE
Next steps for Midi rendering

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#57]
It was so fun and easy to add midi output!

At the present time it does not support other keys than C, but I am confident that after we validate the western branch we can do it.

Please fell free to test it.

I think it is safe to merge it in the beta and/or the master branch, because in case of a bug we can still disable the midi output, or write a caution "this is a beta feature" message.
But only after we decide what to do with the western_branch

***

- [x] test it (-> Tracey)
- [x] decide if the “broken chord” note is alright (I have chosen a short high pitched note) (-> Tracey)
- [x] add support for other keys than C (-> mimizan)
- [x] add support for non-English keys
- [x] see how to change tempo, do we add a constant in main?
- [x] decide if we stick to piano or let the user choose its instrument among a list
- [x] in the documentation, tell that midi rendering is only intended for testing the melody, not for simulating the musical rendering in Sky, especially because pauses are always of the same duration so that the rhythm is not always right (->Tracey) https://sky.bloomexperiment.com/t/summary-of-output-modes/450?u=cactusflower

**Comment by t1-tracey** [comment]
This is so cool 🤩

**Comment by jmmelko** [comment]
- [ ] test it (-> Tracey)
- [ ] decide if the “broken chord” note is alright (I have chosen a short high pitched note) (-> Tracey)
- [ ] add support for other keys than C (-> mimizan)
- [ ] see how to change tempo, do we add a constant in main?
- [ ] decide if we stick to piano or let the user choose its instrument among a list
- [ ] in the documentation, tell that midi rendering is only intended for testing the melody, not for simulating the musical rendering in Sky, especially because pauses are always of the same duration so that the rhythm is not always right (->Tracey)

**Comment by t1-tracey** [comment]
ah is it ok if I move the checklist in the first post so it registers the count?

**Comment by t1-tracey** [comment]
oh yeah and I'll put the documentation here for now:

https://sky.bloomexperiment.com/c/music-sheet-maker/documentation?kb=active

**Comment by jmmelko** [comment]
Abo it doremi: everybody use lower case. Since you have introduced regexp, we no longer need uppercase.
Also, the standard is to use si and not ti.
Ti is used, I think, to remove the ambiguity with sol because of the first letter.
Let me know if you really want to use Ti.

Btw, I have heard that German use H instead of B (si), while B is used for Bb (si bémol). I don’t think we could easily support this because of the ambiguity of B. Also interrogating os.env.lang does not always work (for instance on my Pythonista installation it returns ˋen´ Even though iOS is fr)


Did you know that Inuits don’t have the B note because it cannot be played out of from flutes carved in seal’s bone? And that for native Australians octave order is reversed because low pitched notes are considered to be sacred? 🤪😷🤒🤤🚑

**Comment by t1-tracey** [comment]
Wow that is so interesting about the Inuits and indigenous Australians ☺️ I didn’t even know. And hmm I see - about the Germanic naming, I will get back to this in the other issue.


On 20 Dec 2019, at 5:27 pm, jmmelko <notifications@github.com> wrote:

﻿

Abo it doremi: everybody use lower case. Since you have introduced regexp, we no longer need uppercase.
Also, the standard is to use si and not ti.
Ti is used, I think, to remove the ambiguity with sol because of the first letter.
Let me know if you really want to use Ti.

Btw, I have heard that German use H instead of B (si), while B is used for Bb (si bémol). I don’t think we could easily support this because of the ambiguity of B. Also interrogating os.env.lang does not always work (for instance on my Pythonista installation it returns ˋen´ Even though iOS is fr)

Did you know that Inuits don’t have the B note because it cannot be played out of from flutes carved in seal’s bone? And that for native Australians octave order is reversed because low pitched notes are considered to be sacred? 🤪😷🤒🤤🚑

**Comment by jmmelko** [comment]
Don’t be ashamed: you didn’t know it because it was a joke.
But I admit that it sounds realistic. Too many hours watching wildlife and anthropology documentaries I suppose.

**Comment by t1-tracey** [comment]
😅 wow it does sound realistic though~

**Comment by t1-tracey** [comment]
I'm excited for support in keys other than C! I manually transposed in MuseScore and it worked 😍

**Comment by t1-tracey** [comment]
hmm I can't seem to hear the short high pitched note in muse score, that's ok though. I was going to suggest silence instead of a high-pitched note but I think it does make sense, much better for detecting errors.

**Comment by jmmelko** [comment]
If you don’t hear it that’s because you have a high-frequency hearing loss due to presbycusis (https://en.m.wikipedia.org/wiki/Presbycusis) . I’m sorry to learn that 😔

LOL, I’m joking 🥳. That’s probably a bug.
Can you give me the sheet so I can make a test? Thanks.

**Comment by jmmelko** [comment]
> I'm excited for support in keys other than C! I manually transposed in MuseScore and the song notes were right, it worked 😍

Mmm... you mean you compared midi rendering of MuseScore vs midi rendering of the python script?

OMG😱 I have just read about MusicXML... please divert your eyes and don’t tell me we have to also support this format. Nobody really use it, right?
Right? 😰

**Comment by t1-tracey** [comment]
Ohh I just meant I played the .mid file in MuseScore, and MuseScore had a transpose function so I transposed to the right key and the notes were all correct 👍 (which meant they were correct in C major too, we just need to be able to transpose them to other keys)

Lol I think basic midi support is ok for now! It’s already so cool to have midi, we weren’t expecting that

**Comment by t1-tracey** [comment]
Sure I can give the sheets when I’m back at computer, I don’t have the sheet with mistakes though I had edited it

**Comment by jmmelko** [comment]
I have added the possibility to change the tempo and the instrument, but by the devs only through the properties of the Song class. This program was not intended for midi purposes, after all.

Now, we have to decide how non-English keys will be managed. Internally, the render_midi method assumes English notation, which is logical since midi was standadized by american and japanese.

I think... since we do *not* output songs in Jianpu nor dorémi... and most people use English notation anyway, and since Sky does not have an internal notation system for the musical key (I mean, not special symbol, Sky's world is mostly populated by illiterate children), we should translate the musical key to English at some place.

But we must not erase it completely since we have to display it in its original language  when we ask the user to choose a key.

So we should write a get_english_notation(key, input_mode) method in the Parser, or at least use the Parser, to translate the key, for a given  input_mode

**Comment by jmmelko** [comment]
Ok, I made an attempt to translate english keys. I have added methods to the note parsers.
It works with non decorated keys, and all western keys.
I am not sure it works with sharp or flat non-English keys (eg 1b, 1#, do#, dob), but that's because inverse Sky->Westen translation is incomplete.

Another brainless method would be to add translation dictionaries, for base names of notes only.

I dunno.

**Comment by t1-tracey** [comment]
Wow 😮 I'm just going to post my test songs from earlier first

# Last Christmas
```
# # Last # Christ - # mas # # I # gave # you # my # heart
DF#A E2 E2 D2 . A E2 E2 F#2 D2
# but # the # ve - # ry # next # day
A A DF#BE2 E2 F#2 D2
# you # gave # it # a - # way
D2 C#2 D2 C#2 B
# this # year # # to # save # me # from # tears
EGBF#2 E2 . B F#2 G2 F#2 E2
# I'll # give # it # to # some - # one # spe - # cial
D2 EAC#2 D2 D2 C#2 D2 C#2 A
```

# Threshold

```
# first part
F#1A1C#2F#2 G#1 F#1A1C#2 E2-F#2-G#2
E1G#1B1E2A2 B1 F#1A1C#2 G#2
F#1B1D#2F#2B2 A1 E1G#1B1 C#2 E1 G#2
E1A1C#2G#2 E1A1C#2A2
# second part
F#1A1C#2F#2 F#1-G#1 F#1A1C#2 E2-G#1F#2-G#2
E1B1F#2A2 E2B2 E1A1C#2D#3
F#1B1D#3F#2B2 E3 E3 G#1C#3E2G#2D#3 G#2C#3
A2 B2
A2-G#2 A2-G#2 G#2 B2-A2 A2-G#2
```

# winter piano

```
# intro
F1 Bb1 Eb2 G1 Bb1 Eb2 Ab1 Bb1
F1 Bb1 Eb2 G1 Bb1 Eb2 Ab1 Bb1
F1 Bb1 Eb2 G1 Bb1 Eb2 Ab1 Bb1
F1 Bb1 Eb2 G1 Bb1 Eb2 Ab1 Bb1
# # do you # wanna # build a
Ab1Eb2G2 . . . . . . .
#  snowman?
. . . . . . Bb1Bb2 .
# come # on let's # go and
. . . . . . . .
# play
. . . . . . D2D3 .
# # I never see you anymore
. . . . . . . .
# # # # come out the door
Ab2 G2 Ab1 . . . . .
Ab2 G2 G1 . . . . .
# it's like you've gone away
. . . . . . . .
. . . . . . . .
# we used to be best buddies
. . . . . . . .
# and now we're not
. . . . . . . .
# I wish you would tell me why
. . . . . . . .
. . . . . . . .
# do you wanna build a snowman?
. . . . . . . .
. . . . . . . .
Bb2Bb1 . . . . . . .
# it doesn't have to be a snowman
. . . . . . . .
Ab2Ab1 . . . . . . .
# okay bye
. . . . . . . .
```

**Comment by t1-tracey** [comment]
hmm the support for keys seems to add the right key signature to the MIDI file, but it doesn't shift the notes up

this is the sheet for threshold. The key signature is right, but the notes aren't (the first chord in the bottom should be F# A C# rather than D F A)

![threshold_midi](https://user-images.githubusercontent.com/22441348/71315192-16dfe180-24ab-11ea-92f9-5cfbd261853a.png)

**Comment by jmmelko** [comment]
Most likely my programs defaults the key to C somewhere because of an Except statement.
I’ll check.

**Comment by t1-tracey** [comment]
I’ve tested MIDI and it works as expected now 🤩

Ah yeah in Sky, B is almost one octave up from C too. In some parts of the game (such as voice calls), it is changed to G G# A Bb B C Db D Eb E F F# instead

No transposition is okay, and I’m good with handling the merging 👍

**Comment by t1-tracey** [comment]
I think the high pitched broken chord is ok, and the key shift in midi works as expected now!
