### ISSUE TITLE
Commits not present in the western scales branch

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#61]
Besides the obvious, I have introduced a few enhancements into the master and beta branches, that are in NOT the western branch. Pushing them from the master to the western_scale branch would be dangereous, I think, since western is ahead master on several other aspects.
Even though GitHub is smart, I fear that these improvements may get lost after we merge western_scale into the master. So I will list them below so we can check that they are still in the master after the merging:

- [x] in main.css: font-size: 1.0em
- [x] new file: css/warning.txt
- [x] new file:  elements/readme_elements.txt
- [x] in instruments.py: optional PIL import with definition of no_PIL_module variable
- [x] in main.py : compact writing of for ask_for_mode()
- [x] in main.py: new version of load_file(), including a use of re and only one return parameter
- [x] in main.py: compact value assignement of the ENABLED_MODES constant
- [x] in main.py: compact writing of allowed song notations (for mode in InputModes...)
- [x] in main.py: use of the new method read_lines()
- [x] in notes.py: optional PIL import
- [x] in songs.py: optional PIL import and "if no_PIL_module == False:" statement in __init__() and "if no_PIL_module == True" statement in write_png function
- [x] new file  python/tools/readme_tools.txt

**Comment by t1-tracey** [comment]
Difficulties of version control lol. I think in future, how about we have stable, beta and tests-passed for releases? tests-passed is where we will commit the latest changes (rather than focussing on separate branches for a specific feature e.g. western-scales, midi) 

I was originally planning to merge western-scales into beta, and created a separate branch because I didn’t want to interrupt any changes you might be working on in beta

We could make smaller branches like western-scales but only intended to be temporary and not as big as this has gotten 😓 

I’ll come and try to help review though^^

This also came to mind (major would be stable, minor would be beta, and tests-passed will be patches once we have tests):

https://thepavilion.io/t/plugin-versioning/1627/8

> - The basic format is MAJOR.MINOR.PATCH . This means that bugfixes should increment the PATCH digit, small features should bump the MINOR digit, and an overhaul :wink: or something which changes a lot of previously built stuff (backward-incompatible changes) should bump the MAJOR digit.
>
> - The initial release should be 0.1.0.
>
> - If there is a major release, the minor and patch versions will be reset to 0. i.e. if a major release occurs after 1.4.7 it would be 2.0.0.
>
> - No changes should be introduced to the released code after release.
> 
> A pre release version should be denoted by appending a hyphen to the actual version. i.e. 1.0.0-alpha 1 etc.
>
> - The major version will be bumped even if a small backwards incompatible change is introduced to the codebase. My suggestion personally would be not to do that in the first place and instead, create a new major release branch, add more changes and release the version once a substantial set of features is introduced.
>
> The spec should be strictly followed in order to get the benefits it promises.
> 
> - The version should be bumped to 1.0.0 if your software is already running in production.

**Comment by t1-tracey** [comment]
*Changed the name of tests-passed to dev, tests-passed was a name inspired from another open source software project, I couldn’t think of another name

**Comment by jmmelko** [comment]
Welcome back! Trips are always a bit exhausting whatever your age, so take your time.
Whatever you think is best.

Actually there is a feature of Git called “cherry picking” that allows you to choose one by one the commits you want to pull on either branch. But sadly this feature is not implemented in the web nor in the desktop version of GitHub.
A single dev branch is OK, as long as we don’t have several developers working simultaneously on different major overhauls, but this has never been the case.

**Comment by t1-tracey** [comment]
can you check if these changes have remained in the western branch?

**Comment by t1-tracey** [comment]
then I'll delete western branch. oh and I meant to ask, which branch is `midi` extended from? (master, beta or western scales)

**Comment by jmmelko** [comment]
I think midi is a spin-off from beta.
The changes are very localized so if we want to merge midi into the new beta, a few copy-paste could do.

**Comment by jmmelko** [comment]
> can you double check if these changes have remained in the western branch?

Yes, they are in the new beta after you merged western scales into it.
So you can carry in with the spring cleaning of the branches.

**Comment by t1-tracey** [comment]
Hehe ok! I’ll take care of this branch, will delete the western-scales branch and start a new dev branch

**Comment by t1-tracey** [comment]
About the branches, does this sound ok? https://sky.bloomexperiment.com/t/music-sheet-maker-github-branches/457 Feel free to make suggestions

**Comment by jmmelko** [comment]
That’s great, excepted maybe, rename “stable” to “archive”?
Otherwise it would suggest that master is unstable. 
I mean, if I was a new user, I would either download stable, to remain serene, or dev to get the hottest features, and forget about that bland master branch.

**Comment by t1-tracey** [comment]
:joy: lol, I think archive makes sense, I’m ok with that 👍

**Comment by t1-tracey** [comment]
ok I have managed to rename `stable` to `archive`! and I forgot to reply to this but yeah I have heard of cherry picking in the command line! I haven't used it myself yet though.
