### ISSUE TITLE
Ascii output in Western or Jianpu notations does not support musical keys

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#67]
As explained elsewhere, the ascii rendering functions use static inverse position_maps starting with the C key in Sky.

We should add support for other keys.

To be more precise:

* output to TXT in Sky notation works, as expected since the song is internally coded in Sky, and the TXT is just another rendering mode
* what does not work is Sky->western conversion. This should be out of the scope of this program, but I like it. For instance if someone transcribe a song on the sky music forum and I want to play it on a real piano or just store it using an universal musical notation.

There are two ways of doing this:
* adding the key as an input parameter and using a circular shift, in a new method of the Song class
* rely on methods already in the NoteParser classes, those using conversion between number base representations

- [X] In the meantime we should print a warning in main.

**Comment by jmmelko** [comment]
To be more precise:
* output to TXT in Sky notation works, as expected since the song is internally coded in Sky, and the TXT is just another rendering mode
* what does not work is Sky->western conversion. This should be out of the scope of this program, but I like it. For instance if someone transcribe a song on the sky music forum and I want to play it on a real piano or just store it using an universal musical notation.

**Comment by t1-tracey** [comment]
I think we will have to add the musical_key as a property of `Song()` rather than just in self.headers (would this help MIDI output in keys other than C too?)

**Comment by jmmelko** [comment]
I suppose you’re right.
The key is not just a decoration, i.e. not a meta attribute. It is more like a deciphering key, i.e. vital information on how to read the song.
Also, the Song object is instantiated after we determine the key, and after that the key is never changed again.
So yes.
Just make sure of the following:
* the object has the default value C if none is given
* the key is universally understood, whether we are using Jianpu or Western notation, ie make sure that Jianpu TXT rendering does not expect a digit instead of a letter.

**Comment by t1-tracey** [comment]
Ah that sounds good to me 👍

Sent from my iPad

**Comment by jmmelko** [comment]
I will do it.
I will also change a bit main so that the recommended musical key is asked earlier.
As I did in the dev branch.

**Comment by jmmelko** [comment]
I have made a simplified diagram of how calculate_coordinate_for_note() works. I suppose that if we want to handle keys in ascii rendering, we will have to do the same operations in the reverse order :-(

![calculate_coordinate](https://user-images.githubusercontent.com/17069038/71322058-020f4800-24c3-11ea-899a-d5a60a3cd0ed.png)

**Comment by t1-tracey** [comment]
Haha that’s a nice diagram 😊 ill assign myself the task of making the algorithm for coordinate to note name, given a key.

**Comment by t1-tracey** [comment]
we can close this for now since wont fix (can always be reopened later)
