### ISSUE TITLE
Make chord_skygrid a separate class

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#75]
right now it is a static structure of dictionaries. it was a rough thing that suited when I first used it, but now the project has grown. 

My next medium-term goals are:

- to turn it into a class 
- add methods to access its highlighted-frames, etc.
- update all references to it being a dictionary

I think after these next issues, we can start defining a spec for how we want the discord bot to behave (e.g. DM the user like the Sky bug reports?) and move towards MVP for v1 😮

**Comment by jmmelko** [comment]
Yeah, I am also having that growing feeling that the Sky grid is not used properly. 

Can we make the change a bit later? I suggest working on the dev branch for that.

**Comment by t1-tracey** [comment]
Yep we can work on the change a bit later, I just wanted to announce ahead

Sent from my iPad

**Comment by t1-tracey** [comment]
https://sky.bloomexperiment.com/t/make-chord-skygrid-a-separate-class/299

**Comment by t1-tracey** [comment]
Won’t work on these right now but I have noted them down

**Comment by jmmelko** [comment]
Fixed!
