### ISSUE TITLE
Use of branches

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#80]
Ah just about the branches, I intended that we will both commit all changes into dev. And every so often, when nothing is broken, we will pull request dev into beta (as a minor release). This was to avoid having to add a hot fix to all branches because it causes merge conflicts later on ;-;

**Comment by t1-tracey** [comment]
maybe my documentation was confusing, I'll open an issue anyway so we can talk about each of our preferences

**Comment by t1-tracey** [comment]
but we can get back to it later. I am going to take a short break over Xmas too, I have relatives over from interstate. tgc is taking a break too for 2 weeks. I wanted to keep working on this actually but everything taking more than I anticipated.

Happy holiday season, JMM :D Thanks for working with me on this project, I've really enjoyed it.

**Comment by jmmelko** [comment]
> Happy holiday season, JMM :D Thanks for working with me on this project, I've really enjoyed it.

Hey.... why are you talking like it’s going to be the end of the world?😨
I have... no, I really enjoy it too!
We all need a rest 🥱
Have fun 🥳 and see you next year 🎅🏻

**Comment by t1-tracey** [comment]
😂🤗🤗

**Comment by t1-tracey** [comment]
Btw ah I get it sounded like it was the end lol - no I just wanted to express my gratitude 😊
I am planning to get back to this after the New Years~

**Comment by t1-tracey** [comment]
ok I think we have resolved this :blush:

**Comment by jmmelko** [comment]
Tracey,

could you please confirm that the new "bot-prototype" is a sandbox for testing the bot installed on your machine, and that future modifications (especially minor universal changes such as #88 and #87) are to be included in the dev branch first.

Thank you :-)

**Comment by t1-tracey** [comment]
Yeah that’s right, I will commit to dev branch once I start working on those. 

bot-prototype is the hacky changes that I had to make to get the python music sheet maker working with the bot – so now I know I will start by rearranging main.py on dev branch

Sent from my iPad

**Comment by jmmelko** [comment]
OK!
