### ISSUE TITLE
Bug when finding song key for notes specified without octaves

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#82]
```
note_parser = EnglishNoteParser()
print(note_parser.calculate_coordinate_for_note('G', 'Ab', note_shift=0))
```

I was doing some testing with Let it go and this case fails, I will look into it

**Comment by t1-tracey** [comment]
ah G was being converted to G4, and considered out of range with Ab4. I have addressed it now in the `handle_note_name_without_octave()` function :blush:

**Comment by t1-tracey** [comment]
ok it's fixed now

**Comment by jmmelko** [comment]
(Yes, I had stumbled onto it also, and found that it was not a bug per se, so I let it go.)

**Comment by t1-tracey** [comment]
oh right, I just remembered that this was an older music sheet of mine. The G *is* supposed to be G2 in this case, I will revert the change

**Comment by t1-tracey** [comment]
Ah for the purposes of `find_key` though, it doesn't produce the right result when the octave number is stripped ;-; 

The key for _Let It Go_ is Ab, which is calculated correctly when G is changed to G2 (with octave shift). However, when parsing as a regular note, G is expected to just be G1.

Ok I have added a special `is_finding_key` flag to the `parse_note` and `calculate_coordinate_for_note` methods, to handle the two cases separately. When `calculate_coordinate_for_note` is being used to find the key, `is_finding_key` should be set to `True`.

**Comment by t1-tracey** [comment]
I have fixed this for English notation but not yet for Jianpu

**Comment by jmmelko** [comment]
Tracey,

Can I apply this fix to other parsers?

Is there any specific reason why you did not do it? I mean, did you encounter any incompatibility/difficulty with notations other than English?

**Comment by t1-tracey** [comment]
yeah it’s ok to fix it for all parsers. I left it to focus on the core bot part. I think the last concern was to check that:
when SongParser() is using `find_key`: 

- `parse_note` needs to have the `is_finding_key = True`
- the methods that get the octave number for Jianpu need to act accordingly when is_finding_key is true (particularly Jianpu's `parse_note` which I didn’t get to checking)

https://github.com/sky-music/sky-python-music-sheet-maker/commit/0c7ab826c61139496ea851a5477ed5b2d5ad41b9

It can be tested with something like:

```
note_parser = noteparser.Jianpu.jianpu()
print(note_parser.calculate_coordinate_for_note('5', '6b', note_shift=0, is_finding_key=True))
```

**Comment by t1-tracey** [comment]
I’m ok with working on this one today though, so we can finish it off

**Comment by t1-tracey** [comment]
I added the change to dev-split, the split of the Jianpu parser was really helpful for doing this and I felt more clear-headed 🤗

**Comment by t1-tracey** [comment]
Ok I've checked through the other note parsers and there's no other override of parse_note, so it's all good.

Thanks for telling me to look over this.

and I have documented briefly here about `parse_note` when `is_finding_key` is True: https://sky.bloomexperiment.com/t/noteparser-documentation/736

**Comment by jmmelko** [comment]
Of course you were the right person to do it the quickest possible , even though my intention was not to put you to work 😅
It’s just that I imagine Alex taking a look at the page and thinking « oh, so many issues, these guys are not ready yet », and walking by...

**Comment by t1-tracey** [comment]
No it’s ok 😆 I don’t think he checks here 👀 anyway I have been making commits to That-Sky-Bot and it’s visible in the server, I’ll ask if he can give permissions to you both too btw
