### ISSUE TITLE
Rewrite paths to /fonts and /elements to include variable for base path

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#87]
In the bot, the base path is `/That-Sky-Bot` and the submodule for the music sheet maker is  `/That-Sky-Bot/sky-python-music-sheet-maker`. 

the `/fonts` and `/elements` paths will need the base current working directory (mycwd) joined in front of them. otherwise they are currently assumed as `/That-Sky-Bot/fonts` etc. when the bot is run

**Comment by jmmelko** [comment]
Do you think we should use relative paths starting from the current working directory or from the directory in which the module is run?
os.getcwd()
or os.path.dirname(os.path.abspath(__file__))
 ?

**Comment by t1-tracey** [comment]
Oh yeah I was just using os.getcwd() in the bot-prototype example

**Comment by jmmelko** [comment]
Here is an alternative code:
self.base_path = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),'..'))
self.empty_chord_png = os.path.normpath(os.path.join(self.base_path,'elements/empty-chord.png'))  # blank harp

There is also the possibility to transform the absolute path into a relative path by adding:

self.empty_chord_png = os.path.relpath(self.empty_chord_png, start=os.getcwd())

Pros: does not assume that the name of the base directory will always be  'sky-python-music-sheet-maker'
Cons: assumes that the directory of python files is at the same hierarchical level than the directory of graphical elements (/x/y/z/python /x/y/z/elements)

I'll let you decide and make the changes. txs.

**Comment by t1-tracey** [comment]
Thanks for the tips, I will work on this as my next task. might take some time for me though.
(I will need to work on this issue for dev branch to work again)

**Comment by jmmelko** [comment]
Tracey, I think that you forgot to apply the fix to notes.py in the dev branch.

I am uploading a new version, tell me if it’s ok

**Comment by t1-tracey** [comment]
Oops I must have forgotten, thank you

Sent from my iPad

**Comment by t1-tracey** [comment]
I think this is ok now :blush: feel free to reopen/fix if there's any more that have been missed
