### ISSUE TITLE
Text width is limited to harp width in PNG output

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#88]
Comments (aka lyrics) are rendered as a PNG image with a width equal to the one of the harp. So text longer than the width is clipped.

We should do one of the following:
* reduce font size to match the width (I don’t like it);
* implement text wrapping when the text (aka comment aka lyrics) is longer than the harp width (aka icon width). I think it is Okay if we accept left alignement of the text, BUT this trick will not do if the number of lines becomes too large;
* let the text overlap with the next one (ie spill on the right); that would mean that PNG objects (pillow.Image objects) will have a non constant width (size(0)) for lyrics. But this is not a problem, I think, since all resizing and carriage returns are calculated using the harp width. In principle it might even be possible to print the next lyric after the end of previous one  .

**Comment by t1-tracey** [comment]
Oh yeah I was just thinking option 3, let the text spill on the right — if there’s a single line comment with a # at the start. 

Yeah the text wrapping can work too if the comment is not too long (I hadn’t thought of that) hmm. I’ll let you decide.

**Comment by jmmelko** [comment]
Should be fixed. To be tested.

**Comment by t1-tracey** [comment]
ok this works nice :blush:

```
# asodfihasoidfhoasdifhoasidfhoias # asodfihasodifhoaisdhfoisadhf # s

```
![another test](https://user-images.githubusercontent.com/22441348/73332210-1d3b5780-42ba-11ea-83ae-9c7730cfdd76.png)

![QWERT test](https://user-images.githubusercontent.com/22441348/73332227-304e2780-42ba-11ea-8d34-65cf14dc90eb.png)
