### ISSUE TITLE
find_key hesitates between QWERTY and English in some rare cases

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#90]
If the song only contains English note names included in the SkyKeyboard characters, find_key cannot tell which notation is used.

Ambiguity could be lifted in some cases by detecting alteration characters (flats and sharps) and/or octave numbers, as SkyKeyboard uses neither of these.

**Comment by jmmelko** [comment]
Ok, I fixed it using a method already used for discriminating between English and Sky.

**Comment by t1-tracey** [comment]
Aw no worries i think that’s fine 😊
