### ISSUE TITLE
Add methods to write images to buffer (without needing to write to a filepath)

### ISSUE THREAD

**Issue by t1-tracey** [sky-music/sky-python-music-sheet-maker#94]
How to write to a file without needing to write it to disk
```py
buffer = StringIO()
# use it as any other file here to write to it
buffer.seek(0) # reset the reader to the beginning
await channel.send(file=discord.File(buffer, "filename"))
```

**Comment by jmmelko** [comment]
Or we can always write to the buffer by default, and transfer it to disk afterwards only if the script is not run on Discord.

**Comment by t1-tracey** [comment]
Ok I will try writing to the buffer by default 😊 haven't gotten to do this yet, just saw your message now oops

**Comment by t1-tracey** [comment]
Ugh sorry I visit the official server every so often and the official server makes me feel 🤮 I don’t feel like producing a program for them. I started seeing a psychologist too recently and I feel better. but I feel so demotivated about program I don’t know why

**Comment by jmmelko** [comment]
I thought we were doing this for Sky’s players, not for TGC or Discord. What are you calling “official server” exactly?

I can try to implement the buffer thing in the dev branch if you like. For the rendering functions at least.
And also fix this relative path thing.

You’ve done a lot recently.

Just tell me which branch I should start from. By default I will use dev.

**Comment by t1-tracey** [comment]
Aw yeah thanks Mimizan. We are doing it for Sky's players, thanks for reminding me. (And sorry I mean the official Sky server.)

Ok yep writing to a buffer or file (rather than a file path) can be done in the dev branch. In `responder.py`, I think `write_song` can be renamed to `write_song_to_filepath` (it will be only used in the Desktop program) and new method(s) for `write_song_to_file` are made. 

Then what I had in mind is the specific code for writing song to a file, is removed from `write_song_to_filepath` and put in `write_song_to_file`. And `write_song_to_filepath` will then call `write_song_to_file` and receive a file. (Meanwhile, the bot can also call `write_song_to_file` to send the files to Discord)

**Comment by jmmelko** [comment]
Do we agree that only PNGs will be sent to the Discord channel? Or at least, that only 1 file type will be sent per player request, not several as the command line program?

**Comment by jmmelko** [comment]
It will take slightly more time than anticipated because I have to use BytesIO with pillow (PIL) and I have never done that.

**Comment by t1-tracey** [comment]
at first I was thinking of the bot being able to send all the output modes (PNG, ASCII, midi) and I enabled PNG and ASCII in the bot prototype. I’m not really sure how to structure write_song_to_file for that. And that’s ok, take your time, we don’t have a time limit on this 🤗

**Comment by t1-tracey** [comment]
Edit: yeah one type as per player request^^

**Comment by jmmelko** [comment]
Btw: do we use a buffer because file writing to disk is forbidden with the bot? Or is it to make things more straightforward and avoid having to clean the disk periodically?

**Comment by t1-tracey** [comment]
Yeah it is just to avoid having to delete the files periodically -

I had trouble with unique file names (when I was testing the bot prototype on Discord, e.g. test.png was overwriting each other) so it was suggested a timestamp could be added to the file names and delete them after writing to disk. 

Or if the files aren’t needed again later, they could be written to a buffer and sent to Discord without having to write to disk (and gave the example of the code in the top of the issue)

**Comment by jmmelko** [comment]
Ok,

I now need to understand where does the channel object come from. I suppose it will be passed as a parameter to the send_song_to_channel method, and stored inside the responder object? Or I can leave the “await channel” line commented for you to edit later.

Also, the write_songs_to_file can be simplified, I think, by creating a generic write_song_to_file subfunction, because in the current state it is made of the same piece of code repeated over and over.

**Comment by t1-tracey** [comment]
Wow thank you JMM. I will look through it, and yep the channel is specific to the bot, I can handle that.

**Comment by t1-tracey** [comment]
This has been working great on the command line. I’ll handle the await.channel and implementing Responder in the bot, in another issue
