### ISSUE TITLE
Default song directory in Responder

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#97]
I think it would be nice to add optional arguments to the head of responder so that the command line user can change the song directory to whatever name they want:

    def __init__(self, dir_in='test_songs', dir_out='songs_out'):

        self.song_dir_in = dir_in
        self.song_dir_out = dir_out

What do you think?

**Comment by t1-tracey** [comment]
Yeah the choice is yours 😊 that seems handy to me 👍
