### ISSUE TITLE
What does refactor parse_song to be in Song class mean?

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#98]
Hi Tracey,

I see that in responder.py you have written TODOs and among them:
“ refactor song_lines, song_keys, parse_song to be in Song class”

I apologize in advance if I have misunderstood your intentions and thus if the rest of my message is irrelevant.

The Song object is for a Sky Song, i.e. a list of Instrument objects, where each instrument essentially contains highlighted notes according to a 3*5 grid, as well as some song properties such as the key, the title, etc.

So, IMO, parsing functions should *not* be included in the Song object. The ability to parse or to be parsed is not a property or a function of a Song. They apply to what the user provides, which is *not* a Song (I insist on the uppercase S): it is merely a list of ascii characters, that the Parser object tries to interpret, to produce a Song object.

After that, the Song object lives independently of how it was parsed.

I know that, at the beginning, there was a Renderer class, which was the entity symmetrical to Parser. But we have decided to make it a method of Song. Actually I decided this without asking you first (sorry) but at the time the code was in a less more advanced state. Anyways, I think we have done enough merging.

Actually, I think it was a good idea to create Song but it was disputable to delete Renderer. We could have kept it as a tool to apply on a Song object.

Of course, this is only my point of view. You may have a very good reason to do otherwise.

My other fear is code management : parser is 1000 line long and song is already 700 line long.

**Comment by t1-tracey** [comment]
Hi mimizan 😊 I understand your concern, thanks for raising this^^ oh yeah, at time - I think song_lines was just a global variable in main.py and I wasn’t sure where to put it.  

and yeah i had noticed parser is over 1000 lines too 😂 i was concerned too, but don’t really know how to best structure things. Are you ok with continuing the discussion with Strawb? they asked if they can help in any way and they brought this up:

![Sky music sheet maker server on Discord](https://user-images.githubusercontent.com/22441348/73237090-a5e9c300-41e8-11ea-8adc-bae5781b0e1f.png)

**Comment by t1-tracey** [comment]
Re-reading again and Strawb's message, I am with you on not putting parse_song in Song class ^^ I think I wrote that comment after I wasn’t sure where to song_keys and song_lines (after rewriting main.py to be in a class)
