### ISSUE TITLE
Create Renderer class

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#99]
As suggested by Strawb, we could:

* create the Renderer class
* while keeping the Song class

Pros: more logical
Cons: the Song class would essentially be empty, as >85% of the code is for rendering (PNG, Midi, etc); it would just be an object storing the instruments, ie a big variable.

TODOs:

- [x] relocate write_xxxx methods from Song to Renderer
- [x] relocate formatting properties (such as HTML_note width, SVG_viewport, png_harp_size, midi_bpm)
- [x] relocate or duplicate imports (mido, PIL)
- [x] Song should be a mandatory input argument for \_\_init\_\_() in Renderer
- [x] in the relocates methods, replace self.xxxx by self.song.xxxxx
- [x] check the comments in the code for TODOs such as “move this to Renderer”
- [x] do not forget to use or define directory_base to write files
- [x] move render methods from `Instruments.py` etc.

**Comment by jmmelko** [comment]
I will assign this issue to Strawb provided Tracey acknowledges him.

**Comment by jmmelko** [comment]
TODOs:

- [ ] relocate write_xxxx methods from Song to Renderer
- [ ] relocate formatting properties (such as HTML_note width, SVG_viewport, png_harp_size, midi_bpm)
- [ ] relocate or duplicate imports (mido, PIL)
- [ ] Song should be a mandatory input argument for \_\_init\_\_() in Renderer
- [ ] in the relocates methods, replace self.xxxx by self.song.xxxxx

**Comment by t1-tracey** [comment]
I'll work on this now

**Comment by jmmelko** [comment]
Ok so I will focus on the cog
